import { SlideData } from './types';

export interface CarouselTemplate {
  id: string;
  name: string;
  description: string;
  category: string;
  thumbnail?: string;
  slides: Omit<SlideData, 'id'>[];
}

// 5 Perfect Templates - Quality over Quantity
// Each template is professionally designed and works for everything
export const BOLD_TEMPLATES: CarouselTemplate[] = [
  // Template 1: Bold Educational (Light) - Viral carousel style
  {
    id: 'bold-light-education',
    name: '📚 Bold Educational',
    description: 'Viral educational carousel style - light background with bold typography',
    category: 'Education',
    slides: [
      {
        type: 'cover',
        title: 'YOUR WEBSITE',
        subtitle: 'HAS ONLY 3SECONDS',
        category: '',
        accentColor: '#FFA500',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1.3,
        backgroundColor: '#E8E8E8',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'subtitle', 'media'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'PEOPLE SCAN',
        content: '<p style="font-size: 1.4em; line-height: 1.5;"><strong style="background: var(--slide-accent); color: var(--slide-bg); padding: 4px 12px; display: inline-block;">NOT READ</strong></p><p style="margin-top: 1rem;">Most visitors don\'t read every word. They skim for value, clarity, and quick answers.</p>',
        emoji: '',
        category: '',
        accentColor: '#FFA500',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1.2,
        backgroundColor: '#EFEFEF',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content', 'media'],
        customBlocks: [],
      },
    ],
  },

  // Template 2: Minimalist Professional - Apple-like clarity
  {
    id: 'pro-minimalist-clarity',
    name: '🎯 Minimalist Professional',
    description: 'Ultra-minimal, white space driven - perfect for professional content',
    category: 'Professional',
    slides: [
      {
        type: 'cover',
        title: 'DESIGN WITH',
        subtitle: 'CLARITY',
        category: '',
        accentColor: '#007AFF',
        handle: '@yourhandle',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.4,
        backgroundColor: '#FFFFFF',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'subtitle'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'REMOVE NOISE',
        content: '<p>Every extra element competes for attention. Strip away what\'s non-essential.</p>',
        emoji: '',
        category: '',
        accentColor: '#007AFF',
        handle: '@yourhandle',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.1,
        backgroundColor: '#F8F9FA',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content'],
        customBlocks: [],
      },
    ],
  },

  // Template 3: Business Growth - Modern and engaging
  {
    id: 'business-growth',
    name: '📈 Business Growth',
    description: 'Modern business-focused design - perfect for strategies and insights',
    category: 'Business',
    slides: [
      {
        type: 'cover',
        title: 'BUSINESS GROWTH',
        subtitle: 'STRATEGIES THAT WORK',
        category: 'Business',
        accentColor: '#FF6B9D',
        handle: '@yourhandle',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.4,
        backgroundColor: '#FFFFFF',
        textColor: '#1A1A1A',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'subtitle'],
        customBlocks: [],
        textAlign: 'center',
      },
      {
        type: 'content',
        title: 'KEY INSIGHTS',
        content: '<p>Focus on what moves the needle. Measure what matters.</p>',
        emoji: '',
        category: 'Business',
        accentColor: '#FF6B9D',
        handle: '@yourhandle',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.2,
        backgroundColor: '#F8F9FA',
        textColor: '#1A1A1A',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content'],
        customBlocks: [],
        textAlign: 'left',
      },
    ],
  },

  // Template 4: Visual Infographic - Icon-based storytelling
  {
    id: 'visual-infographic',
    name: '🎨 Visual Infographic',
    description: 'Icon-driven visual storytelling - perfect for processes and tips',
    category: 'Visual',
    slides: [
      {
        type: 'cover',
        title: 'THE PROCESS',
        subtitle: 'STEP BY STEP',
        category: 'Visual',
        accentColor: '#FFD700',
        handle: '@yourhandle',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.5,
        backgroundColor: '#0B0F19',
        textColor: '#FFFFFF',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'subtitle'],
        customBlocks: [],
        textAlign: 'center',
      },
      {
        type: 'visual',
        title: 'KEY STEPS',
        icon: 'lightbulb',
        content: '<ul><li>Start with clarity</li><li>Focus on value</li><li>Measure results</li></ul>',
        infographicData: {
          items: ['Start with clarity', 'Focus on value', 'Measure results'],
          layout: 'icon-cards',
        },
        category: 'Visual',
        accentColor: '#FFD700',
        handle: '@yourhandle',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.2,
        backgroundColor: '#0B0F19',
        textColor: '#FFFFFF',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['icon', 'title', 'infographic'],
        customBlocks: [],
        textAlign: 'center',
      },
    ],
  },

  // Template 5: Dark Modern - Trendy and bold
  {
    id: 'dark-modern',
    name: '🌙 Dark Modern',
    description: 'Trendy dark theme with vibrant accents - perfect for modern content',
    category: 'Modern',
    slides: [
      {
        type: 'cover',
        title: 'MODERN',
        subtitle: 'DESIGN THINKING',
        category: 'Modern',
        accentColor: '#FFD700',
        handle: '@yourhandle',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.6,
        backgroundColor: '#0B0F19',
        textColor: '#FFFFFF',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'subtitle'],
        customBlocks: [],
        textAlign: 'center',
      },
      {
        type: 'content',
        title: 'BOLD IDEAS',
        content: '<p>Think different. Create impact. Stand out.</p>',
        emoji: '',
        category: 'Modern',
        accentColor: '#FFD700',
        handle: '@yourhandle',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.3,
        backgroundColor: '#1A1A2E',
        textColor: '#FFFFFF',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content'],
        customBlocks: [],
        textAlign: 'center',
      },
    ],
  },

  // --- HIGH-CONVERTING: Carousel Templates ---

  // Hook + Story: Bold provocative opening, clean narrative follow-through
  {
    id: 'hook-story',
    name: '🪝 Hook + Story',
    description: 'Bold opening hook with a provocative question, followed by narrative slides with clean typography',
    category: 'High-Converting',
    slides: [
      {
        type: 'cover',
        title: 'WHAT IF EVERYTHING',
        subtitle: 'YOU KNEW WAS WRONG?',
        category: '',
        accentColor: '#FF6B35',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1.4,
        backgroundColor: '#0A1628',
        textColor: '#FFFFFF',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'subtitle', 'media'],
        customBlocks: [],
        textAlign: 'center',
      },
      {
        type: 'content',
        title: 'HERE\'S THE TRUTH',
        content: '<p style="font-size: 1.1em; line-height: 1.7;">Most people follow the crowd. The ones who <strong style="color: #FF6B35;">question everything</strong> are the ones who change the game.</p>',
        emoji: '',
        category: '',
        accentColor: '#FF6B35',
        handle: '@yourhandle',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.2,
        backgroundColor: '#0D1B2A',
        textColor: '#E2E8F0',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content', 'media'],
        customBlocks: [],
        textAlign: 'left',
      },
    ],
  },

  // Listicle: "X Things You Need to Know" numbered format with icons
  {
    id: 'listicle',
    name: '📋 Listicle',
    description: '"X Things You Need to Know" format with numbered slides and icons',
    category: 'High-Converting',
    slides: [
      {
        type: 'cover',
        title: '7 THINGS',
        subtitle: 'YOU NEED TO KNOW',
        category: '',
        accentColor: '#7C3AED',
        handle: '@yourhandle',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.3,
        backgroundColor: '#FFFFFF',
        textColor: '#1A1A2E',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'subtitle', 'media'],
        customBlocks: [],
        textAlign: 'center',
      },
      {
        type: 'content',
        title: '01',
        content: '<p style="font-size: 1.1em; line-height: 1.6;"><strong style="color: #7C3AED;">Start with why.</strong></p><p style="margin-top: 0.5rem; color: #64748B;">People don\'t buy what you do — they buy why you do it.</p>',
        emoji: '',
        category: '',
        accentColor: '#7C3AED',
        handle: '@yourhandle',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.2,
        backgroundColor: '#F8F7FF',
        textColor: '#1A1A2E',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content', 'media'],
        customBlocks: [],
        textAlign: 'left',
      },
    ],
  },

  // Data-Driven: Stats-focused with large numbers and supporting text
  {
    id: 'data-driven',
    name: '📊 Data-Driven',
    description: 'Stats-focused layout with large numbers and supporting insights',
    category: 'High-Converting',
    slides: [
      {
        type: 'cover',
        title: 'THE DATA',
        subtitle: 'DOESN\'T LIE',
        category: '',
        accentColor: '#06D6A0',
        handle: '@yourhandle',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.5,
        backgroundColor: '#0F172A',
        textColor: '#F0FDF4',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'subtitle', 'media'],
        customBlocks: [],
        textAlign: 'center',
      },
      {
        type: 'content',
        title: '73%',
        content: '<p style="font-size: 1em; line-height: 1.6;"><strong style="color: #06D6A0;">of decision-makers</strong> say thought leadership content directly influenced their purchasing decisions.</p>',
        emoji: '',
        category: '',
        accentColor: '#06D6A0',
        handle: '@yourhandle',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.4,
        backgroundColor: '#1E293B',
        textColor: '#F0FDF4',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content', 'media'],
        customBlocks: [],
        textAlign: 'center',
      },
    ],
  },

  // Before/After: Comparison format showing transformation
  {
    id: 'before-after',
    name: '🔄 Before / After',
    description: 'Comparison format showing transformation — great for case studies and results',
    category: 'High-Converting',
    slides: [
      {
        type: 'cover',
        title: 'BEFORE vs AFTER',
        subtitle: 'THE TRANSFORMATION',
        category: '',
        accentColor: '#F43F5E',
        handle: '@yourhandle',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.3,
        backgroundColor: '#111827',
        textColor: '#F9FAFB',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'subtitle', 'media'],
        customBlocks: [],
        textAlign: 'center',
      },
      {
        type: 'content',
        title: 'BEFORE',
        content: '<p style="font-size: 1.05em; line-height: 1.6;"><span style="color: #F43F5E;">✗</span> No clear strategy<br/><span style="color: #F43F5E;">✗</span> Inconsistent posting<br/><span style="color: #F43F5E;">✗</span> Low engagement</p><hr style="border-color: #374151; margin: 0.8rem 0;"/><p style="font-size: 1.05em; line-height: 1.6; margin-top: 0.5rem;"><strong style="color: #10B981;">AFTER</strong><br/><span style="color: #10B981;">✓</span> Clear content pillars<br/><span style="color: #10B981;">✓</span> 3x weekly cadence<br/><span style="color: #10B981;">✓</span> 400% reach increase</p>',
        emoji: '',
        category: '',
        accentColor: '#F43F5E',
        handle: '@yourhandle',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.1,
        backgroundColor: '#1F2937',
        textColor: '#F9FAFB',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content', 'media'],
        customBlocks: [],
        textAlign: 'left',
      },
    ],
  },

  // Step-by-Step: Process/tutorial format with numbered steps
  {
    id: 'step-by-step',
    name: '🪜 Step-by-Step',
    description: 'Process and tutorial format with clearly numbered steps',
    category: 'High-Converting',
    slides: [
      {
        type: 'cover',
        title: 'HOW TO DO IT',
        subtitle: 'A STEP-BY-STEP GUIDE',
        category: '',
        accentColor: '#3B82F6',
        handle: '@yourhandle',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.3,
        backgroundColor: '#1E1B4B',
        textColor: '#E0E7FF',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'subtitle', 'media'],
        customBlocks: [],
        textAlign: 'center',
      },
      {
        type: 'content',
        title: 'STEP 1',
        content: '<p style="font-size: 1.1em; line-height: 1.6;"><strong style="color: #3B82F6;">Define your goal.</strong></p><p style="margin-top: 0.5rem;">Be specific about the outcome. Vague goals produce vague results.</p>',
        emoji: '',
        category: '',
        accentColor: '#3B82F6',
        handle: '@yourhandle',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.2,
        backgroundColor: '#252262',
        textColor: '#E0E7FF',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content', 'media'],
        customBlocks: [],
        textAlign: 'left',
      },
    ],
  },

  // Neon Tech Deep Dive: Dark techy design with neon accents — exact match to microfrontends carousel
  {
    id: 'neon-tech-deep-dive',
    name: '\u26A1 Neon Tech Deep Dive',
    description: 'Dark, techy design with neon accents \u2014 perfect for educational deep dives and technical content',
    category: 'Premium',
    slides: [
      {
        type: 'cover',
        title: 'THE <em>ULTIMATE</em> GUIDE',
        subtitle: '<div style="font-family:var(--font-roboto-mono),monospace;font-size:0.45em;color:#9BA8C0;line-height:1.7;">The complete guide to scaling your craft, systems, and impact.<br/><span style="color:rgba(232,255,71,0.6);">\u2192 10 slides \u00B7 Swipe to learn</span></div><div style="display:flex;justify-content:space-between;align-items:center;margin-top:24px;font-family:var(--font-roboto-mono),monospace;font-size:0.4em;"><span style="color:rgba(255,255,255,0.5);letter-spacing:0.1em;">by <span style="color:#E8FF47;letter-spacing:0.05em;">Your Name</span></span><span style="color:#E8FF47;letter-spacing:0.1em;">01/10 \u2192</span></div>',
        category: '',
        accentColor: '#E8FF47',
        handle: '',
        fontFamily: 'var(--font-bebas-neue)',
        fontScale: 1.6,
        backgroundColor: '#0D1120',
        textColor: '#EEF2FF',
        titleColor: '#EEF2FF',
        slideLabel: 'Deep Dive Series',
        slideLabelColor: '#E8FF47',
        showNoise: true,
        glowColor: 'rgba(232,255,71,0.12)',
        glowPosition: 'top-right' as const,
        slidePadding: 36,
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center' as const,
        elementOrder: ['slideLabel', 'title', 'subtitle', 'media'],
        customBlocks: [],
        borderWidth: 1,
        borderColor: 'rgba(232,255,71,0.15)',
        borderStyle: 'solid' as const,
        borderRadius: 14,
        freePositioning: false,
        slideJustify: 'between' as const,
      },
      {
        type: 'content',
        title: 'What is a <em>Key Concept?</em>',
        content: '<p style="border-left: 3px solid #00D4FF; padding-left: 16px; color: #9BA8C0; font-size: 0.95em; line-height: 1.8;">Your audience needs context before diving into details. Start with a clear definition that grounds the entire conversation.</p><div style="background: rgba(0,212,255,0.06); border: 1px solid rgba(0,212,255,0.15); border-radius: 10px; padding: 14px 18px; margin-top: 16px; color: #00D4FF; font-size: 0.85em; line-height: 1.6;">\uD83D\uDCA1 Think of it like splitting a complex problem into focused, manageable pieces that work seamlessly together.</div>',
        emoji: '',
        category: '',
        accentColor: '#00D4FF',
        handle: '@yourhandle',
        fontFamily: 'var(--font-epilogue)',
        fontScale: 1.1,
        backgroundColor: '#080C18',
        textColor: '#EEF2FF',
        titleColor: '#EEF2FF',
        slideLabel: 'The Definition',
        slideLabelColor: '#00D4FF',
        slideNumber: undefined,
        totalSlides: undefined,
        slidePadding: 36,
        glowColor: 'rgba(0,212,255,0.09)',
        glowPosition: 'bottom-right' as const,
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center' as const,
        elementOrder: ['slideCounter', 'slideLabel', 'title', 'content', 'media'],
        customBlocks: [],
        borderWidth: 1,
        borderColor: 'rgba(0,212,255,0.12)',
        borderStyle: 'solid' as const,
        borderRadius: 14,
        freePositioning: false,
      },
      {
        type: 'content',
        title: 'Why the <em>Old Approach</em> Fails',
        content: '<div style="display:flex;flex-direction:column;gap:14px;"><div style="display:flex;gap:12px;align-items:flex-start;"><div style="width:32px;height:32px;flex-shrink:0;border-radius:7px;background:rgba(255,77,109,0.1);border:1px solid rgba(255,77,109,0.2);display:flex;align-items:center;justify-content:center;font-size:14px;">\uD83D\uDC0C</div><div><div style="font-size:1.05em;font-weight:700;color:#EEF2FF;margin-bottom:2px;">Wasted Time</div><div style="font-family:monospace;font-size:0.85em;color:#9BA8C0;line-height:1.6;">Most people spend hours on the wrong approach. One change = full rebuild.</div></div></div><div style="display:flex;gap:12px;align-items:flex-start;"><div style="width:32px;height:32px;flex-shrink:0;border-radius:7px;background:rgba(255,77,109,0.1);border:1px solid rgba(255,77,109,0.2);display:flex;align-items:center;justify-content:center;font-size:14px;">\uD83D\uDD12</div><div><div style="font-size:1.05em;font-weight:700;color:#EEF2FF;margin-bottom:2px;">Locked Into Old Methods</div><div style="font-family:monospace;font-size:0.85em;color:#9BA8C0;line-height:1.6;">Stuck with the approach chosen years ago. No escape without full rewrite.</div></div></div><div style="display:flex;gap:12px;align-items:flex-start;"><div style="width:32px;height:32px;flex-shrink:0;border-radius:7px;background:rgba(255,77,109,0.1);border:1px solid rgba(255,77,109,0.2);display:flex;align-items:center;justify-content:center;font-size:14px;">\uD83D\uDD78\uFE0F</div><div><div style="font-size:1.05em;font-weight:700;color:#EEF2FF;margin-bottom:2px;">Tight Coupling</div><div style="font-family:monospace;font-size:0.85em;color:#9BA8C0;line-height:1.6;">Everything tangled together. Nobody wants to touch it.</div></div></div></div>',
        emoji: '',
        category: '',
        accentColor: '#FF4D6D',
        handle: '@yourhandle',
        fontFamily: 'var(--font-epilogue)',
        fontScale: 1.1,
        backgroundColor: '#0D1120',
        textColor: '#EEF2FF',
        titleColor: '#EEF2FF',
        slideLabel: 'The Problem',
        slideLabelColor: '#FF4D6D',
        slideNumber: undefined,
        totalSlides: undefined,
        slidePadding: 36,
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center' as const,
        elementOrder: ['slideCounter', 'slideLabel', 'title', 'content', 'media'],
        customBlocks: [],
        borderWidth: 1,
        borderColor: 'rgba(255,77,109,0.15)',
        borderStyle: 'solid' as const,
        borderRadius: 14,
        freePositioning: false,
      },
      {
        type: 'content',
        title: '<em>5 Core</em> Principles',
        content: '<div style="display:flex;flex-direction:column;gap:11px;"><div style="display:flex;gap:12px;align-items:flex-start;"><span style="font-family:monospace;font-size:0.75em;color:#E8FF47;opacity:0.6;min-width:22px;padding-top:2px;">01</span><div><div style="font-size:1.05em;font-weight:700;color:#EEF2FF;">Start With the End in Mind</div><div style="font-family:monospace;font-size:0.82em;color:#9BA8C0;line-height:1.5;">Define your outcome before choosing your tools.</div></div></div><div style="display:flex;gap:12px;align-items:flex-start;"><span style="font-family:monospace;font-size:0.75em;color:#E8FF47;opacity:0.6;min-width:22px;padding-top:2px;">02</span><div><div style="font-size:1.05em;font-weight:700;color:#EEF2FF;">Keep It Simple</div><div style="font-family:monospace;font-size:0.82em;color:#9BA8C0;line-height:1.5;">Complexity is the enemy of execution. Cut the noise.</div></div></div><div style="display:flex;gap:12px;align-items:flex-start;"><span style="font-family:monospace;font-size:0.75em;color:#E8FF47;opacity:0.6;min-width:22px;padding-top:2px;">03</span><div><div style="font-size:1.05em;font-weight:700;color:#EEF2FF;">Measure Everything</div><div style="font-family:monospace;font-size:0.82em;color:#9BA8C0;line-height:1.5;">What gets measured gets improved. Track your progress.</div></div></div><div style="display:flex;gap:12px;align-items:flex-start;"><span style="font-family:monospace;font-size:0.75em;color:#E8FF47;opacity:0.6;min-width:22px;padding-top:2px;">04</span><div><div style="font-size:1.05em;font-weight:700;color:#EEF2FF;">Iterate Fast</div><div style="font-family:monospace;font-size:0.82em;color:#9BA8C0;line-height:1.5;">Ship, learn, improve. Perfection is the enemy of done.</div></div></div><div style="display:flex;gap:12px;align-items:flex-start;"><span style="font-family:monospace;font-size:0.75em;color:#E8FF47;opacity:0.6;min-width:22px;padding-top:2px;">05</span><div><div style="font-size:1.05em;font-weight:700;color:#EEF2FF;">Share Knowledge</div><div style="font-family:monospace;font-size:0.82em;color:#9BA8C0;line-height:1.5;">Teaching others solidifies your own understanding.</div></div></div></div>',
        emoji: '',
        category: '',
        accentColor: '#E8FF47',
        handle: '@yourhandle',
        fontFamily: 'var(--font-epilogue)',
        fontScale: 1.05,
        backgroundColor: '#07080F',
        textColor: '#EEF2FF',
        titleColor: '#EEF2FF',
        slideLabel: 'The Foundation',
        slideLabelColor: '#E8FF47',
        slideNumber: undefined,
        totalSlides: undefined,
        slidePadding: 36,
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center' as const,
        elementOrder: ['slideCounter', 'slideLabel', 'title', 'content', 'media'],
        customBlocks: [],
        borderWidth: 1,
        borderColor: 'rgba(232,255,71,0.1)',
        borderStyle: 'solid' as const,
        borderRadius: 14,
        freePositioning: false,
      },
      {
        type: 'content',
        title: 'Staying <em>Fast</em> at Scale',
        content: '<div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;"><div style="background:rgba(232,255,71,0.04);border:1px solid rgba(232,255,71,0.1);border-radius:10px;padding:14px;"><div style="font-size:0.95em;font-weight:700;color:#E8FF47;margin-bottom:5px;">Research</div><div style="font-family:monospace;font-size:0.78em;color:#9BA8C0;line-height:1.5;">Understand the landscape before making any moves.</div></div><div style="background:rgba(0,212,255,0.04);border:1px solid rgba(0,212,255,0.1);border-radius:10px;padding:14px;"><div style="font-size:0.95em;font-weight:700;color:#00D4FF;margin-bottom:5px;">Plan</div><div style="font-family:monospace;font-size:0.78em;color:#9BA8C0;line-height:1.5;">Map your strategy with clear milestones and deadlines.</div></div><div style="background:rgba(255,149,0,0.04);border:1px solid rgba(255,149,0,0.1);border-radius:10px;padding:14px;"><div style="font-size:0.95em;font-weight:700;color:#FF9500;margin-bottom:5px;">Execute</div><div style="font-family:monospace;font-size:0.78em;color:#9BA8C0;line-height:1.5;">Take consistent action. Small steps compound over time.</div></div><div style="background:rgba(255,77,109,0.04);border:1px solid rgba(255,77,109,0.1);border-radius:10px;padding:14px;"><div style="font-size:0.95em;font-weight:700;color:#FF4D6D;margin-bottom:5px;">Review</div><div style="font-family:monospace;font-size:0.78em;color:#9BA8C0;line-height:1.5;">Reflect on what worked and iterate on what didn\'t.</div></div></div>',
        emoji: '',
        category: '',
        accentColor: '#E8FF47',
        handle: '@yourhandle',
        fontFamily: 'var(--font-epilogue)',
        fontScale: 1.1,
        backgroundColor: '#0D1120',
        textColor: '#EEF2FF',
        titleColor: '#EEF2FF',
        slideLabel: 'Performance',
        slideLabelColor: '#E8FF47',
        slideNumber: undefined,
        totalSlides: undefined,
        slidePadding: 36,
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center' as const,
        elementOrder: ['slideCounter', 'slideLabel', 'title', 'content', 'media'],
        customBlocks: [],
        borderWidth: 1,
        borderColor: 'rgba(232,255,71,0.1)',
        borderStyle: 'solid' as const,
        borderRadius: 14,
        freePositioning: false,
      },
      {
        type: 'content',
        title: '<em>Independent</em> Pipeline',
        content: '<div style="display:flex;flex-direction:column;gap:11px;"><div style="display:flex;gap:12px;align-items:center;"><div style="width:10px;height:10px;border-radius:50%;background:#E8FF47;flex-shrink:0;"></div><div style="flex:1;"><div style="font-size:1.05em;font-weight:700;color:#EEF2FF;">Step 1: Audit Your Current State</div><div style="font-family:monospace;font-size:0.82em;color:#9BA8C0;line-height:1.4;">Know where you stand before making changes.</div></div><span style="font-family:monospace;font-size:0.65em;color:#FF9500;background:rgba(255,149,0,0.08);border:1px solid rgba(255,149,0,0.15);padding:3px 8px;border-radius:4px;white-space:nowrap;">DAY 1</span></div><div style="display:flex;gap:12px;align-items:center;"><div style="width:10px;height:10px;border-radius:50%;background:#00D4FF;flex-shrink:0;"></div><div style="flex:1;"><div style="font-size:1.05em;font-weight:700;color:#EEF2FF;">Step 2: Define Your Goals</div><div style="font-family:monospace;font-size:0.82em;color:#9BA8C0;line-height:1.4;">Specificity beats vague ambition every time.</div></div><span style="font-family:monospace;font-size:0.65em;color:#FF9500;background:rgba(255,149,0,0.08);border:1px solid rgba(255,149,0,0.15);padding:3px 8px;border-radius:4px;white-space:nowrap;">WEEK 1</span></div><div style="display:flex;gap:12px;align-items:center;"><div style="width:10px;height:10px;border-radius:50%;background:#FF9500;flex-shrink:0;"></div><div style="flex:1;"><div style="font-size:1.05em;font-weight:700;color:#EEF2FF;">Step 3: Build the System</div><div style="font-family:monospace;font-size:0.82em;color:#9BA8C0;line-height:1.4;">Create repeatable processes, not one-off wins.</div></div><span style="font-family:monospace;font-size:0.65em;color:#FF9500;background:rgba(255,149,0,0.08);border:1px solid rgba(255,149,0,0.15);padding:3px 8px;border-radius:4px;white-space:nowrap;">MONTH 1</span></div><div style="display:flex;gap:12px;align-items:center;"><div style="width:10px;height:10px;border-radius:50%;background:#FF4D6D;flex-shrink:0;"></div><div style="flex:1;"><div style="font-size:1.05em;font-weight:700;color:#EEF2FF;">Step 4: Scale What Works</div><div style="font-family:monospace;font-size:0.82em;color:#9BA8C0;line-height:1.4;">Double down on proven strategies. Cut the rest.</div></div><span style="font-family:monospace;font-size:0.65em;color:#FF9500;background:rgba(255,149,0,0.08);border:1px solid rgba(255,149,0,0.15);padding:3px 8px;border-radius:4px;white-space:nowrap;">ONGOING</span></div></div>',
        emoji: '',
        category: '',
        accentColor: '#FF9500',
        handle: '@yourhandle',
        fontFamily: 'var(--font-epilogue)',
        fontScale: 1.05,
        backgroundColor: '#0D1120',
        textColor: '#EEF2FF',
        titleColor: '#EEF2FF',
        slideLabel: 'DevOps',
        slideLabelColor: '#FF9500',
        slideNumber: undefined,
        totalSlides: undefined,
        slidePadding: 36,
        glowColor: 'rgba(255,149,0,0.08)',
        glowPosition: 'top-left' as const,
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center' as const,
        elementOrder: ['slideCounter', 'slideLabel', 'title', 'content', 'media'],
        customBlocks: [],
        borderWidth: 1,
        borderColor: 'rgba(255,149,0,0.12)',
        borderStyle: 'solid' as const,
        borderRadius: 14,
        freePositioning: false,
      },
      {
        type: 'content',
        title: '5 <em>Pitfalls</em> to Avoid',
        content: '<div style="display:flex;flex-direction:column;gap:12px;"><div style="display:flex;gap:10px;align-items:flex-start;"><span style="color:#FF4D6D;font-weight:700;font-size:0.95em;min-width:16px;padding-top:1px;">\u2715</span><div><div style="font-size:1.05em;font-weight:700;color:#EEF2FF;">Going Too Fast Without a Plan</div><div style="font-family:monospace;font-size:0.82em;color:#9BA8C0;line-height:1.5;">Speed without direction is just chaos in disguise.</div></div></div><div style="display:flex;gap:10px;align-items:flex-start;"><span style="color:#FF4D6D;font-weight:700;font-size:0.95em;min-width:16px;padding-top:1px;">\u2715</span><div><div style="font-size:1.05em;font-weight:700;color:#EEF2FF;">Ignoring the Fundamentals</div><div style="font-family:monospace;font-size:0.82em;color:#9BA8C0;line-height:1.5;">Fancy tactics fail without strong foundations.</div></div></div><div style="display:flex;gap:10px;align-items:flex-start;"><span style="color:#FF4D6D;font-weight:700;font-size:0.95em;min-width:16px;padding-top:1px;">\u2715</span><div><div style="font-size:1.05em;font-weight:700;color:#EEF2FF;">Trying to Do Everything Alone</div><div style="font-family:monospace;font-size:0.82em;color:#9BA8C0;line-height:1.5;">Leverage community, tools, and delegation.</div></div></div><div style="display:flex;gap:10px;align-items:flex-start;"><span style="color:#FF4D6D;font-weight:700;font-size:0.95em;min-width:16px;padding-top:1px;">\u2715</span><div><div style="font-size:1.05em;font-weight:700;color:#EEF2FF;">Not Measuring Results</div><div style="font-family:monospace;font-size:0.82em;color:#9BA8C0;line-height:1.5;">If you can\'t measure it, you can\'t improve it.</div></div></div><div style="display:flex;gap:10px;align-items:flex-start;"><span style="color:#FF4D6D;font-weight:700;font-size:0.95em;min-width:16px;padding-top:1px;">\u2715</span><div><div style="font-size:1.05em;font-weight:700;color:#EEF2FF;">Giving Up Too Early</div><div style="font-family:monospace;font-size:0.82em;color:#9BA8C0;line-height:1.5;">Consistency beats intensity. Show up every day.</div></div></div></div>',
        emoji: '',
        category: '',
        accentColor: '#FF4D6D',
        handle: '@yourhandle',
        fontFamily: 'var(--font-epilogue)',
        fontScale: 1.05,
        backgroundColor: '#07080F',
        textColor: '#EEF2FF',
        titleColor: '#EEF2FF',
        slideLabel: 'Watch Out',
        slideLabelColor: '#FF4D6D',
        slideNumber: undefined,
        totalSlides: undefined,
        slidePadding: 36,
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center' as const,
        elementOrder: ['slideCounter', 'slideLabel', 'title', 'content', 'media'],
        customBlocks: [],
        borderWidth: 1,
        borderColor: 'rgba(255,77,109,0.15)',
        borderStyle: 'solid' as const,
        borderRadius: 14,
        freePositioning: false,
      },
      {
        type: 'content',
        title: '',
        content: '<div style="display:flex;flex-direction:column;justify-content:center;gap:24px;min-height:600px;"><div style="font-size:10em;color:rgba(232,255,71,0.04);position:absolute;top:-20px;left:20px;line-height:1;font-family:serif;pointer-events:none;">\u201C</div><p style="font-size:1.3em;font-weight:800;line-height:1.35;color:#EEF2FF;position:relative;letter-spacing:-0.025em;">The difference between those who <span style="color:#E8FF47;">succeed</span> and those who don\'t isn\'t talent \u2014 it\'s the <span style="color:#E8FF47;">system</span> they follow.</p><div style="font-family:monospace;font-size:0.75em;color:rgba(255,255,255,0.6);position:relative;line-height:1.6;">Inspired by <span style="color:rgba(232,255,71,0.5);">your favorite author</span><br/>Replace with your own source<br/><span style="opacity:0.4;">or original insight</span></div></div>',
        emoji: '',
        category: '',
        accentColor: '#E8FF47',
        handle: '@yourhandle',
        fontFamily: 'var(--font-epilogue)',
        fontScale: 1.1,
        backgroundColor: '#090C18',
        textColor: '#EEF2FF',
        titleColor: '#EEF2FF',
        slideLabel: 'Key Insight',
        slideLabelColor: '#E8FF47',
        slideNumber: undefined,
        totalSlides: undefined,
        slidePadding: 36,
        glowColor: 'rgba(232,255,71,0.06)',
        glowPosition: 'center' as const,
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center' as const,
        elementOrder: ['slideCounter', 'slideLabel', 'title', 'content', 'media'],
        customBlocks: [],
        borderWidth: 1,
        borderColor: 'rgba(232,255,71,0.12)',
        borderStyle: 'solid' as const,
        borderRadius: 14,
        freePositioning: false,
      },
      {
        type: 'content',
        title: '<em>Old Way</em> vs New Way',
        content: '<div style="display:flex;flex-direction:column;gap:8px;"><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;padding-bottom:8px;border-bottom:1px solid rgba(255,255,255,0.06);"><span style="font-family:monospace;font-size:0.7em;letter-spacing:0.15em;text-transform:uppercase;color:#FF4D6D;">\u274C Old Way</span><span style="font-family:monospace;font-size:0.7em;letter-spacing:0.15em;text-transform:uppercase;color:#E8FF47;">\u2726 New Way</span></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;padding:6px 0;border-bottom:1px solid rgba(255,255,255,0.03);"><span style="color:rgba(255,77,109,0.75);font-size:0.88em;">Guessing what works</span><span style="color:rgba(232,255,71,0.75);font-size:0.88em;">Data-driven decisions</span></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;padding:6px 0;border-bottom:1px solid rgba(255,255,255,0.03);"><span style="color:rgba(255,77,109,0.75);font-size:0.88em;">Working harder</span><span style="color:rgba(232,255,71,0.75);font-size:0.88em;">Working smarter</span></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;padding:6px 0;border-bottom:1px solid rgba(255,255,255,0.03);"><span style="color:rgba(255,77,109,0.75);font-size:0.88em;">One-off efforts</span><span style="color:rgba(232,255,71,0.75);font-size:0.88em;">Repeatable systems</span></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;padding:6px 0;border-bottom:1px solid rgba(255,255,255,0.03);"><span style="color:rgba(255,77,109,0.75);font-size:0.88em;">Doing it all alone</span><span style="color:rgba(232,255,71,0.75);font-size:0.88em;">Leveraging community</span></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;padding:6px 0;"><span style="color:rgba(255,77,109,0.75);font-size:0.88em;">Chasing trends</span><span style="color:rgba(232,255,71,0.75);font-size:0.88em;">Building foundations</span></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;padding:8px 0;margin-top:4px;border-top:1px solid rgba(255,255,255,0.06);"><span></span><span style="color:rgba(232,255,71,0.6);font-size:0.82em;text-align:center;">\u2726 Full end-to-end autonomy</span></div></div>',
        emoji: '',
        category: '',
        accentColor: '#E8FF47',
        handle: '@yourhandle',
        fontFamily: 'var(--font-epilogue)',
        fontScale: 1.1,
        backgroundColor: '#0D1120',
        textColor: '#EEF2FF',
        titleColor: '#EEF2FF',
        slideLabel: 'The Comparison',
        slideLabelColor: '#9BA8C0',
        slideNumber: undefined,
        totalSlides: undefined,
        slidePadding: 36,
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center' as const,
        elementOrder: ['slideCounter', 'slideLabel', 'title', 'content', 'media'],
        customBlocks: [],
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.06)',
        borderStyle: 'solid' as const,
        borderRadius: 14,
        freePositioning: false,
      },
      {
        type: 'cover',
        title: 'SCALE YOUR <em>SYSTEMS,</em> NOT JUST YOUR CODE.',
        subtitle: '<div style="display:flex;flex-direction:column;align-items:center;gap:20px;"><div style="font-family:var(--font-roboto-mono),monospace;font-size:0.45em;color:#9BA8C0;line-height:1.7;max-width:320px;text-align:center;">Build repeatable systems that let your team scale \u2014 from pixel to production.</div><div style="font-family:var(--font-roboto-mono),monospace;font-size:0.4em;letter-spacing:0.2em;text-transform:uppercase;color:#070A10;background:#E8FF47;padding:12px 28px;border-radius:100px;">Follow for more deep dives</div><div style="font-family:var(--font-roboto-mono),monospace;font-size:0.38em;color:rgba(255,255,255,0.45);letter-spacing:0.08em;">By <span style=\'color:#E8FF47\'>Your Name</span> \u00B7 Replace with your source</div></div>',
        category: '',
        accentColor: '#E8FF47',
        handle: '',
        fontFamily: 'var(--font-bebas-neue)',
        fontScale: 1.4,
        textAlign: 'center' as const,
        backgroundColor: '#070A10',
        textColor: '#EEF2FF',
        titleColor: '#EEF2FF',
        slideLabel: 'Takeaway',
        slideLabelColor: '#E8FF47',
        showNoise: true,
        backgroundPattern: 'grid' as const,
        glowColor: 'rgba(232,255,71,0.06)',
        glowPosition: 'center' as const,
        slidePadding: 36,
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center' as const,
        elementOrder: ['slideLabel', 'title', 'subtitle', 'media'],
        customBlocks: [],
        borderWidth: 1,
        borderColor: 'rgba(232,255,71,0.18)',
        borderStyle: 'solid' as const,
        borderRadius: 14,
        freePositioning: false,
        slideJustify: 'between' as const,
      },
    ],
  },
  // Dev Carousel — 16 unique slide designs matching microfrontends carousel patterns
  {
    id: 'dev-carousel',
    name: '⚡ Dev Carousel',
    description: '16-slide dark tech design with icon cards, numbered lists, code blocks, stat grids & more',
    category: 'Premium',
    slides: (() => {
      const Y = '#E8FF47', R = '#FF4D6D', C = '#00D4FF', O = '#FF9500';
      const bg = '#0D1120', bgDark = '#090C18', txt = '#EEF2FF', muted = '#9BA8C0';
      const base = (accent: string, num: number) => ({
        category: '' as const,
        accentColor: accent,
        handle: '@yourhandle',
        fontFamily: 'var(--font-epilogue)',
        fontScale: 1.1,
        backgroundColor: num % 3 === 0 ? bgDark : bg,
        textColor: txt,
        titleColor: txt,
        slideNumber: undefined,
        totalSlides: undefined,
        slidePadding: 36,
        glowColor: `${accent}15`,
        glowPosition: (['top-right', 'bottom-right', 'top-left', 'bottom-left', 'center'] as const)[num % 5],
        mediaType: null as null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center' as const,
        customBlocks: [] as any[],
        borderWidth: 1,
        borderColor: `${accent}20`,
        borderStyle: 'solid' as const,
        borderRadius: 14,
        freePositioning: false,
      });
      return [
        // 01 — Cover: badge + display title + subtitle footer
        {
          type: 'cover' as const,
          title: 'YOUR <em>TOPIC</em>',
          subtitle: `<div style="font-family:var(--font-roboto-mono),monospace;font-size:0.45em;color:${muted};line-height:1.7;">Your subtitle or tagline goes here.<br/><span style="color:${Y}80;">\u2192 Swipe to learn</span></div><div style="display:flex;justify-content:space-between;align-items:center;margin-top:24px;font-family:var(--font-roboto-mono),monospace;font-size:0.4em;"><span style="color:rgba(255,255,255,0.5);letter-spacing:0.1em;">by <span style="color:${Y};">Your Name</span></span><span style="color:${Y};letter-spacing:0.1em;">\u2192</span></div>`,
          ...base(Y, 1),
          fontFamily: 'var(--font-bebas-neue)', fontScale: 1.6,
          slideLabel: 'Series Title', slideLabelColor: Y, showNoise: true,
          glowColor: `${Y}20`, glowPosition: 'top-right' as const,
          elementOrder: ['slideLabel', 'title', 'subtitle', 'media'],
          slideJustify: 'between' as const,
        },
        // 02 — Definition: left-bordered quote + tip callout
        {
          type: 'content' as const,
          title: 'The <em>Definition</em>',
          content: `<p style="border-left:3px solid ${C};padding-left:16px;color:${muted};font-size:0.92em;line-height:1.75;">Your definition or explanation goes here. Ground the audience with a clear, concise overview of the concept.</p><div style="background:rgba(0,212,255,0.06);border:1px solid rgba(0,212,255,0.15);border-radius:10px;padding:14px 18px;margin-top:16px;color:${C};font-size:0.85em;line-height:1.6;">\uD83D\uDCA1 A helpful analogy or key insight that makes the concept click.</div>`,
          emoji: '', slideLabel: 'Definition', slideLabelColor: C,
          ...base(C, 2),
          elementOrder: ['slideCounter', 'slideLabel', 'title', 'content', 'media'],
        },
        // 03 — Problem: icon card rows
        {
          type: 'content' as const,
          title: 'The <em>Problem</em>',
          content: `<div style="display:flex;flex-direction:column;gap:8px;">${[{e:'\uD83D\uDCE6',t:'Pain Point One',d:'Description of the first problem your audience faces.'},{e:'\uD83D\uDD12',t:'Pain Point Two',d:'Description of the second challenge or bottleneck.'},{e:'\uD83D\uDD78\uFE0F',t:'Pain Point Three',d:'Description of the third issue that needs solving.'}].map(c => `<div style="background:rgba(0,0,0,0.25);border:1px solid rgba(255,255,255,0.05);border-radius:10px;padding:12px 16px;display:flex;align-items:flex-start;gap:12px;"><span style="font-size:1.3em;flex-shrink:0;">${c.e}</span><div><div style="font-weight:700;color:${txt};font-size:0.92em;margin-bottom:2px;">${c.t}</div><div style="font-family:var(--font-roboto-mono),monospace;font-size:0.72em;color:${muted};line-height:1.65;">${c.d}</div></div></div>`).join('')}</div>`,
          emoji: '', slideLabel: 'The Problem', slideLabelColor: R,
          ...base(R, 3),
          elementOrder: ['slideCounter', 'slideLabel', 'title', 'content', 'media'],
        },
        // 04 — Numbered list: 01-05 with titles
        {
          type: 'content' as const,
          title: 'Key <em>Principles</em>',
          content: `<div style="display:flex;flex-direction:column;gap:6px;">${[{n:'01',t:'First Principle',d:'Brief explanation of this principle.'},{n:'02',t:'Second Principle',d:'Brief explanation of this principle.'},{n:'03',t:'Third Principle',d:'Brief explanation of this principle.'},{n:'04',t:'Fourth Principle',d:'Brief explanation of this principle.'},{n:'05',t:'Fifth Principle',d:'Brief explanation of this principle.'}].map(r => `<div style="display:flex;gap:14px;align-items:flex-start;padding:4px 0;"><span style="font-family:var(--font-bebas-neue);font-size:1.6em;line-height:1;color:${Y};flex-shrink:0;min-width:28px;">${r.n}</span><div><div style="font-weight:700;color:${txt};font-size:0.92em;">${r.t}</div><div style="font-family:var(--font-roboto-mono),monospace;font-size:0.7em;color:${muted};line-height:1.65;margin-top:1px;">${r.d}</div></div></div>`).join('')}</div>`,
          emoji: '', slideLabel: 'Foundation', slideLabelColor: Y,
          ...base(Y, 4),
          elementOrder: ['slideCounter', 'slideLabel', 'title', 'content', 'media'],
        },
        // 05 — Card rows with right-aligned labels
        {
          type: 'content' as const,
          title: '<em>Team</em> Structure',
          content: `<div style="display:flex;flex-direction:column;gap:8px;">${[{e:'\uD83D\uDCBB',t:'Module One'},{e:'\uD83D\uDD0D',t:'Module Two'},{e:'\uD83D\uDC64',t:'Module Three'}].map(c => `<div style="background:rgba(0,0,0,0.25);border:1px solid rgba(255,255,255,0.05);border-radius:10px;padding:14px 18px;display:flex;align-items:center;justify-content:space-between;"><div style="display:flex;align-items:center;gap:10px;"><span style="font-size:1.1em;">${c.e}</span><span style="font-weight:700;color:${txt};font-size:0.95em;">${c.t}</span></div><div style="text-align:right;"><div style="font-family:var(--font-roboto-mono),monospace;font-size:0.68em;color:${O};font-weight:600;letter-spacing:0.05em;">Label</div><div style="font-family:var(--font-roboto-mono),monospace;font-size:0.6em;color:${O};opacity:0.7;">sublabel</div></div></div>`).join('')}</div><p style="font-family:var(--font-roboto-mono),monospace;font-size:0.72em;color:${muted};line-height:1.65;margin-top:14px;">Summary description of the ownership model.</p>`,
          emoji: '', slideLabel: 'Structure', slideLabelColor: O,
          ...base(O, 5),
          elementOrder: ['slideCounter', 'slideLabel', 'title', 'content', 'media'],
        },
        // 06 — Code block
        {
          type: 'content' as const,
          title: 'The <em>Pattern</em>',
          content: `<p style="color:${muted};font-size:0.9em;line-height:1.75;">Explanation of the core pattern.</p><div style="background:rgba(0,0,0,0.35);border:1px solid rgba(255,255,255,0.06);border-radius:8px;padding:14px 16px;margin-top:14px;font-family:var(--font-roboto-mono),monospace;font-size:0.72em;line-height:1.7;color:${muted};"><span style="color:#5A6580;">// Your code example</span><br/><span style="color:${C};">function</span> <span style="color:${Y};">example</span>() {<br/>&nbsp;&nbsp;<span style="color:${C};">return</span> <span style="color:${Y};">result</span>;<br/>}</div>`,
          emoji: '', slideLabel: 'Pattern', slideLabelColor: Y,
          ...base(Y, 6),
          elementOrder: ['slideCounter', 'slideLabel', 'title', 'content', 'media'],
        },
        // 07 — Code block
        {
          type: 'content' as const,
          title: '<em>Advanced</em> Usage',
          content: `<p style="color:${muted};font-size:0.9em;line-height:1.75;">Explanation of the advanced technique.</p><div style="background:rgba(0,0,0,0.35);border:1px solid rgba(255,255,255,0.06);border-radius:8px;padding:14px 16px;margin-top:14px;font-family:var(--font-roboto-mono),monospace;font-size:0.72em;line-height:1.7;color:${muted};"><span style="color:${C};">async function</span> <span style="color:${Y};">process</span>() {<br/>&nbsp;&nbsp;<span style="color:${C};">const</span> data = <span style="color:${C};">await</span> <span style="color:${Y};">fetch</span>();<br/>&nbsp;&nbsp;<span style="color:${C};">return</span> data;<br/>}</div>`,
          emoji: '', slideLabel: 'Deep Dive', slideLabelColor: C,
          ...base(C, 7),
          elementOrder: ['slideCounter', 'slideLabel', 'title', 'content', 'media'],
        },
        // 08 — Code block: streaming
        {
          type: 'content' as const,
          title: '<em>Progressive</em> Loading',
          content: `<p style="color:${muted};font-size:0.9em;line-height:1.75;">Explanation of incremental rendering.</p><div style="background:rgba(0,0,0,0.35);border:1px solid rgba(255,255,255,0.06);border-radius:8px;padding:14px 16px;margin-top:14px;font-family:var(--font-roboto-mono),monospace;font-size:0.72em;line-height:1.7;color:${muted};">&lt;<span style="color:${Y};">Wrapper</span> fallback={&lt;Loading /&gt;}&gt;<br/>&nbsp;&nbsp;&lt;<span style="color:${Y};">Content</span> /&gt;<br/>&lt;/<span style="color:${Y};">Wrapper</span>&gt;</div>`,
          emoji: '', slideLabel: 'Technique', slideLabelColor: R,
          ...base(R, 8),
          elementOrder: ['slideCounter', 'slideLabel', 'title', 'content', 'media'],
        },
        // 09 — Code block: mutation
        {
          type: 'content' as const,
          title: 'Practical <em>Example</em>',
          content: `<p style="color:${muted};font-size:0.9em;line-height:1.75;">A real-world usage example.</p><div style="background:rgba(0,0,0,0.35);border:1px solid rgba(255,255,255,0.06);border-radius:8px;padding:14px 16px;margin-top:14px;font-family:var(--font-roboto-mono),monospace;font-size:0.72em;line-height:1.7;color:${muted};"><span style="color:${C};">async function</span> <span style="color:${Y};">submit</span>(data) {<br/>&nbsp;&nbsp;<span style="color:${C};">await</span> db.<span style="color:${Y};">save</span>(data);<br/>&nbsp;&nbsp;<span style="color:${Y};">refresh</span>();<br/>}</div>`,
          emoji: '', slideLabel: 'Example', slideLabelColor: O,
          ...base(O, 9),
          elementOrder: ['slideCounter', 'slideLabel', 'title', 'content', 'media'],
        },
        // 10 — Pill tags
        {
          type: 'content' as const,
          title: 'Best <em>Practices</em>',
          content: `<div style="display:flex;flex-wrap:wrap;gap:6px;margin-bottom:14px;">${['Practice One','Practice Two','Practice Three','Practice Four','Practice Five','Practice Six','Practice Seven','Practice Eight'].map(t => `<span style="font-family:var(--font-roboto-mono),monospace;font-size:0.7em;padding:5px 12px;border-radius:100px;background:rgba(255,255,255,0.04);border:1px solid rgba(255,255,255,0.08);color:${muted};">${t}</span>`).join('')}</div><p style="color:${muted};font-size:0.88em;line-height:1.75;">Summary of the overarching principle behind these practices.</p>`,
          emoji: '', slideLabel: 'Practices', slideLabelColor: Y,
          ...base(Y, 10),
          elementOrder: ['slideCounter', 'slideLabel', 'title', 'content', 'media'],
        },
        // 11 — Stats grid: 2x2
        {
          type: 'content' as const,
          title: 'The <em>Numbers</em>',
          content: `<div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;">${[{n:'##',d:'Metric one description',c:C},{n:'##',d:'Metric two description',c:Y},{n:'##',d:'Metric three description',c:O},{n:'##',d:'Metric four description',c:R}].map(s => `<div style="background:rgba(0,0,0,0.25);border:1px solid rgba(255,255,255,0.05);border-radius:8px;padding:14px;"><div style="font-family:var(--font-bebas-neue);font-size:2em;line-height:1;color:${s.c};">${s.n}</div><div style="font-family:var(--font-roboto-mono),monospace;font-size:0.65em;color:${muted};margin-top:4px;line-height:1.5;">${s.d}</div></div>`).join('')}</div>`,
          emoji: '', slideLabel: 'Impact', slideLabelColor: C,
          ...base(C, 11),
          elementOrder: ['slideCounter', 'slideLabel', 'title', 'content', 'media'],
        },
        // 12 — Before/After comparison
        {
          type: 'content' as const,
          title: 'Before vs <em>After</em>',
          content: `<div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;"><div style="background:rgba(0,0,0,0.2);border-radius:8px;padding:14px;border:1px solid rgba(255,255,255,0.04);"><div style="font-family:var(--font-roboto-mono),monospace;font-size:0.65em;letter-spacing:0.15em;text-transform:uppercase;color:${R};font-weight:600;margin-bottom:8px;">Before</div>${['Old approach item 1','Old approach item 2','Old approach item 3'].map(t => `<div style="font-family:var(--font-roboto-mono),monospace;font-size:0.7em;color:${muted};line-height:1.8;">${t}</div>`).join('')}<div style="font-weight:600;color:${R};font-size:0.78em;margin-top:6px;">Result</div></div><div style="background:rgba(0,0,0,0.2);border-radius:8px;padding:14px;border:1px solid rgba(255,255,255,0.04);"><div style="font-family:var(--font-roboto-mono),monospace;font-size:0.65em;letter-spacing:0.15em;text-transform:uppercase;color:${C};font-weight:600;margin-bottom:8px;">After</div>${['New approach item 1','New approach item 2','New approach item 3'].map(t => `<div style="font-family:var(--font-roboto-mono),monospace;font-size:0.7em;color:${muted};line-height:1.8;">${t}</div>`).join('')}<div style="font-weight:600;color:${C};font-size:0.78em;margin-top:6px;">Result</div></div></div>`,
          emoji: '', slideLabel: 'Comparison', slideLabelColor: O,
          ...base(O, 12),
          elementOrder: ['slideCounter', 'slideLabel', 'title', 'content', 'media'],
        },
        // 13 — Arrow checklist
        {
          type: 'content' as const,
          title: 'Common <em>Mistakes</em>',
          content: `<div style="display:flex;flex-direction:column;gap:6px;">${['Mistake number one to avoid','Mistake number two to avoid','Mistake number three to avoid','Mistake number four to avoid','Mistake number five to avoid','Mistake number six to avoid'].map(t => `<div style="font-family:var(--font-roboto-mono),monospace;font-size:0.75em;color:${muted};padding-left:18px;position:relative;line-height:1.75;"><span style="position:absolute;left:0;opacity:0.5;">\u2192</span>${t}</div>`).join('')}</div>`,
          emoji: '', slideLabel: 'Watch Out', slideLabelColor: R,
          ...base(R, 13),
          elementOrder: ['slideCounter', 'slideLabel', 'title', 'content', 'media'],
        },
        // 14 — Comparison grid: two columns
        {
          type: 'content' as const,
          title: '<em>Option A</em> vs <em>Option B</em>',
          content: `<div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;"><div style="background:rgba(0,0,0,0.2);border-radius:8px;padding:14px;border:1px solid rgba(255,255,255,0.04);"><div style="font-family:var(--font-roboto-mono),monospace;font-size:0.65em;letter-spacing:0.15em;text-transform:uppercase;color:${C};font-weight:600;margin-bottom:8px;">Option A</div>${['Feature one','Feature two','Feature three','Feature four','Feature five'].map(t => `<div style="font-family:var(--font-roboto-mono),monospace;font-size:0.7em;color:${muted};line-height:1.8;padding-left:12px;position:relative;"><span style="position:absolute;left:0;opacity:0.4;">\u2022</span>${t}</div>`).join('')}</div><div style="background:rgba(0,0,0,0.2);border-radius:8px;padding:14px;border:1px solid rgba(255,255,255,0.04);"><div style="font-family:var(--font-roboto-mono),monospace;font-size:0.65em;letter-spacing:0.15em;text-transform:uppercase;color:${O};font-weight:600;margin-bottom:8px;">Option B</div>${['Feature one','Feature two','Feature three','Feature four','Feature five'].map(t => `<div style="font-family:var(--font-roboto-mono),monospace;font-size:0.7em;color:${muted};line-height:1.8;padding-left:12px;position:relative;"><span style="position:absolute;left:0;opacity:0.4;">\u2022</span>${t}</div>`).join('')}</div></div>`,
          emoji: '', slideLabel: 'Framework', slideLabelColor: C,
          ...base(C, 14),
          elementOrder: ['slideCounter', 'slideLabel', 'title', 'content', 'media'],
        },
        // 15 — Arrow list: future
        {
          type: 'content' as const,
          title: "What's <em>Next</em>",
          content: `<p style="color:${muted};font-size:0.9em;line-height:1.75;margin-bottom:12px;">Summary of upcoming developments.</p><div style="display:flex;flex-direction:column;gap:6px;">${['Upcoming trend or feature one','Upcoming trend or feature two','Upcoming trend or feature three','Upcoming trend or feature four','Upcoming trend or feature five'].map(t => `<div style="font-family:var(--font-roboto-mono),monospace;font-size:0.75em;color:${muted};padding-left:18px;position:relative;line-height:1.75;"><span style="position:absolute;left:0;opacity:0.5;">\u2192</span>${t}</div>`).join('')}</div>`,
          emoji: '', slideLabel: "What's Next", slideLabelColor: Y,
          ...base(Y, 15),
          elementOrder: ['slideCounter', 'slideLabel', 'title', 'content', 'media'],
        },
        // 16 — CTA
        {
          type: 'cover' as const,
          title: 'LIKED <em>THIS?</em>',
          subtitle: `<div style="display:flex;flex-direction:column;align-items:center;gap:20px;"><div style="font-family:var(--font-roboto-mono),monospace;font-size:0.45em;color:${muted};line-height:1.7;max-width:320px;text-align:center;">Save and share this carousel. Follow for more.</div><div style="font-family:var(--font-roboto-mono),monospace;font-size:0.4em;letter-spacing:0.2em;text-transform:uppercase;color:#070A10;background:${Y};padding:12px 28px;border-radius:100px;">Follow for More</div><div style="font-family:var(--font-roboto-mono),monospace;font-size:0.38em;color:rgba(255,255,255,0.45);letter-spacing:0.08em;">Save \u00B7 Share \u00B7 Comment</div></div>`,
          ...base(Y, 16),
          fontFamily: 'var(--font-bebas-neue)', fontScale: 1.4,
          textAlign: 'center' as const, backgroundColor: '#070A10',
          slideLabel: 'Takeaway', slideLabelColor: Y, showNoise: true,
          backgroundPattern: 'grid' as const,
          glowColor: `${Y}18`, glowPosition: 'center' as const,
          elementOrder: ['slideLabel', 'title', 'subtitle', 'media'],
          slideJustify: 'between' as const, handle: '', borderColor: `${Y}2E`,
        },
      ];
    })(),
  },
];

// Simplified - only perfect templates
export const PRO_TEMPLATES: CarouselTemplate[] = [];
export const INSPIRED_TEMPLATES: CarouselTemplate[] = [];

// Export all templates
export const ALL_TEMPLATES = [...BOLD_TEMPLATES];
