import { SlideData } from './types';

export interface CarouselTemplate {
  id: string;
  name: string;
  description: string;
  category: string;
  thumbnail?: string;
  slides: Omit<SlideData, 'id'>[];
}

// 5 Perfect Templates - Quality over Quantity
// Each template is professionally designed and works for everything
export const BOLD_TEMPLATES: CarouselTemplate[] = [
  // Template 1: Bold Educational (Light) - Viral LinkedIn style
  {
    id: 'bold-light-education',
    name: '📚 Bold Educational',
    description: 'Viral educational carousel style - light background with bold typography',
    category: 'Education',
    slides: [
      {
        type: 'cover',
        title: 'YOUR WEBSITE',
        subtitle: 'HAS ONLY 3SECONDS',
        category: '',
        accentColor: '#FFA500',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1.3,
        backgroundColor: '#E8E8E8',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'subtitle', 'media'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'PEOPLE SCAN',
        content: '<p style="font-size: 1.4em; line-height: 1.5;"><strong style="background: #FFA500; color: #000; padding: 4px 12px; display: inline-block;">NOT READ</strong></p><p style="margin-top: 1rem;">Most visitors don\'t read every word. They skim for value, clarity, and quick answers.</p>',
        emoji: '',
        category: '',
        accentColor: '#FFA500',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1.2,
        backgroundColor: '#EFEFEF',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content', 'media'],
        customBlocks: [],
      },
    ],
  },

  // Template 2: Minimalist Professional - Apple-like clarity
  {
    id: 'pro-minimalist-clarity',
    name: '🎯 Minimalist Professional',
    description: 'Ultra-minimal, white space driven - perfect for professional content',
    category: 'Professional',
    slides: [
      {
        type: 'cover',
        title: 'DESIGN WITH',
        subtitle: 'CLARITY',
        category: '',
        accentColor: '#007AFF',
        handle: '@yourhandle',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.4,
        backgroundColor: '#FFFFFF',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'subtitle'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'REMOVE NOISE',
        content: '<p>Every extra element competes for attention. Strip away what\'s non-essential.</p>',
        emoji: '',
        category: '',
        accentColor: '#007AFF',
        handle: '@yourhandle',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.1,
        backgroundColor: '#F8F9FA',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content'],
        customBlocks: [],
      },
    ],
  },

  // Template 3: Business Growth - Modern and engaging
  {
    id: 'business-growth',
    name: '📈 Business Growth',
    description: 'Modern business-focused design - perfect for strategies and insights',
    category: 'Business',
    slides: [
      {
        type: 'cover',
        title: 'BUSINESS GROWTH',
        subtitle: 'STRATEGIES THAT WORK',
        category: 'Business',
        accentColor: '#FF6B9D',
        handle: '@yourhandle',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.4,
        backgroundColor: '#FFFFFF',
        textColor: '#1A1A1A',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'subtitle'],
        customBlocks: [],
        textAlign: 'center',
      },
      {
        type: 'content',
        title: 'KEY INSIGHTS',
        content: '<p>Focus on what moves the needle. Measure what matters.</p>',
        emoji: '',
        category: 'Business',
        accentColor: '#FF6B9D',
        handle: '@yourhandle',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.2,
        backgroundColor: '#F8F9FA',
        textColor: '#1A1A1A',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content'],
        customBlocks: [],
        textAlign: 'left',
      },
    ],
  },

  // Template 4: Visual Infographic - Icon-based storytelling
  {
    id: 'visual-infographic',
    name: '🎨 Visual Infographic',
    description: 'Icon-driven visual storytelling - perfect for processes and tips',
    category: 'Visual',
    slides: [
      {
        type: 'cover',
        title: 'THE PROCESS',
        subtitle: 'STEP BY STEP',
        category: 'Visual',
        accentColor: '#FFD700',
        handle: '@yourhandle',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.5,
        backgroundColor: '#0B0F19',
        textColor: '#FFFFFF',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'subtitle'],
        customBlocks: [],
        textAlign: 'center',
      },
      {
        type: 'visual',
        title: 'KEY STEPS',
        icon: 'lightbulb',
        content: '<ul><li>Start with clarity</li><li>Focus on value</li><li>Measure results</li></ul>',
        infographicData: {
          items: ['Start with clarity', 'Focus on value', 'Measure results'],
          layout: 'icon-cards',
        },
        category: 'Visual',
        accentColor: '#FFD700',
        handle: '@yourhandle',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.2,
        backgroundColor: '#0B0F19',
        textColor: '#FFFFFF',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['icon', 'title', 'infographic'],
        customBlocks: [],
        textAlign: 'center',
      },
    ],
  },

  // Template 5: Dark Modern - Trendy and bold
  {
    id: 'dark-modern',
    name: '🌙 Dark Modern',
    description: 'Trendy dark theme with vibrant accents - perfect for modern content',
    category: 'Modern',
    slides: [
      {
        type: 'cover',
        title: 'MODERN',
        subtitle: 'DESIGN THINKING',
        category: 'Modern',
        accentColor: '#FFD700',
        handle: '@yourhandle',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.6,
        backgroundColor: '#0B0F19',
        textColor: '#FFFFFF',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'subtitle'],
        customBlocks: [],
        textAlign: 'center',
      },
      {
        type: 'content',
        title: 'BOLD IDEAS',
        content: '<p>Think different. Create impact. Stand out.</p>',
        emoji: '',
        category: 'Modern',
        accentColor: '#FFD700',
        handle: '@yourhandle',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.3,
        backgroundColor: '#1A1A2E',
        textColor: '#FFFFFF',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content'],
        customBlocks: [],
        textAlign: 'center',
      },
    ],
  },
];

// Simplified - only 5 perfect templates
export const PRO_TEMPLATES: CarouselTemplate[] = [];
export const INSPIRED_TEMPLATES: CarouselTemplate[] = [];

// Export all templates (currently just the 5 perfect ones)
export const ALL_TEMPLATES = [...BOLD_TEMPLATES];
