import { SlideData } from './types';

export interface CarouselTemplate {
  id: string;
  name: string;
  description: string;
  category: string;
  thumbnail?: string;
  slides: Omit<SlideData, 'id'>[];
}

// Bold Educational Templates - Inspired by modern infographic style
export const BOLD_TEMPLATES: CarouselTemplate[] = [
  // Template 0: Exact Match - Light Background Bold Style (Like reference image)
  {
    id: 'bold-light-education',
    name: 'ðŸ“Š Bold Educational (Light)',
    description: 'Exact match to viral educational carousel style - light background with orange accents',
    category: 'Education',
    slides: [
      {
        type: 'cover',
        title: 'YOUR WEBSITE',
        subtitle: 'HAS ONLY 3SECONDS',
        category: '',
        accentColor: '#FFA500',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1.3,
        backgroundColor: '#E8E8E8',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'subtitle', 'media'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'PEOPLE SCAN',
        content: '<p style="font-size: 1.4em; line-height: 1.5;"><strong style="background: #FFA500; color: #000; padding: 4px 12px; display: inline-block;">NOT READ</strong></p><p style="margin-top: 1rem;">Most visitors don\'t read every word. They skim for value, clarity, and quick answers. If your website isn\'t instantly clear, they move on.</p>',
        emoji: '',
        category: '',
        accentColor: '#FFA500',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1.2,
        backgroundColor: '#EFEFEF',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content', 'media'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'SLOW WEBSITE!',
        content: '<p style="margin-bottom: 1rem;">If your site takes more than <strong style="background: #FFA500; color: #000; padding: 4px 12px;">3 SECONDS</strong> to load, visitors leave.</p><p>Speed matters as much as design and content.</p>',
        emoji: '',
        category: '',
        accentColor: '#FFA500',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1.2,
        backgroundColor: '#F5F5F5',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content', 'media'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'CALL TO ACTION',
        content: '<p style="background: #6B6B6B; color: #FFF; padding: 2rem; border-radius: 8px; margin-top: 1rem;"><strong style="background: #FFA500; color: #000; padding: 6px 16px; display: inline-block; font-size: 1.3em;">ACTION</strong></p><p style="margin-top: 1.5rem;">People won\'t act unless you show them how. Make it clear, make it easy, and use clear CTAs.</p>',
        emoji: '',
        category: '',
        accentColor: '#FFA500',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1.2,
        backgroundColor: '#EFEFEF',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content', 'media'],
        customBlocks: [],
      },
    ],
  },

  // Template 1: Website Speed Optimization
  {
    id: 'website-speed',
    name: 'âš¡ Website Speed Facts',
    description: 'Bold educational template about website performance',
    category: 'Education',
    slides: [
      {
        type: 'cover',
        title: 'YOUR WEBSITE',
        subtitle: 'HAS ONLY 3 SECONDS',
        category: '',
        accentColor: '#FFA500',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1.2,
        backgroundColor: '#E8E8E8',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'subtitle', 'media'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'PEOPLE SCAN',
        content: '<p style="font-size: 1.2em;"><strong>NOT READ</strong></p><p>Most visitors don\'t read every word. They skim for value, clarity, and quick answers. If your website isn\'t instantly clear, they move on.</p>',
        emoji: '',
        category: '',
        accentColor: '#FF9500',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1,
        backgroundColor: '#F5F5F5',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content', 'media'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'SLOW WEBSITE!',
        content: '<p>If your site takes more than <strong>3 seconds</strong> to load, visitors leave.</p><p>Speed matters as much as design and content.</p>',
        emoji: 'âš ï¸',
        category: '',
        accentColor: '#FF9500',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1,
        backgroundColor: '#F5F5F5',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['emoji', 'title', 'content', 'media'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'CALL TO ACTION',
        content: '<p>People won\'t act unless you <strong>show them how</strong>.</p><ul><li>Make it clear</li><li>Make it easy</li><li>Use strong CTAs</li></ul>',
        emoji: 'ðŸ‘‰',
        category: '',
        accentColor: '#FF9500',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1,
        backgroundColor: '#E8E8E8',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['emoji', 'title', 'content', 'media'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'TAKE ACTION',
        content: '<p><strong>Optimize your website today:</strong></p><ul><li>âœ“ Test your speed</li><li>âœ“ Compress images</li><li>âœ“ Enable caching</li><li>âœ“ Simplify design</li></ul>',
        emoji: 'ðŸš€',
        category: '',
        accentColor: '#FF9500',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1,
        backgroundColor: '#F5F5F5',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['emoji', 'title', 'content', 'media'],
        customBlocks: [],
      },
    ],
  },

  // Template 2: Marketing Psychology
  {
    id: 'marketing-psychology',
    name: 'ðŸ§  Marketing Psychology',
    description: 'Bold template about psychological marketing tactics',
    category: 'Marketing',
    slides: [
      {
        type: 'cover',
        title: '5 PSYCHOLOGY',
        subtitle: 'TRICKS THAT SELL',
        category: '',
        accentColor: '#00D4FF',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1,
        backgroundColor: '#FFFFFF',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'subtitle', 'media'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: '1. SCARCITY',
        content: '<p><strong>"Only 3 left!"</strong></p><p>Limited availability creates <em>urgency</em> and drives faster decisions.</p><p>People fear missing out more than they desire gain.</p>',
        emoji: 'â°',
        category: '',
        accentColor: '#00D4FF',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1,
        backgroundColor: '#FFFFFF',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content', 'media'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: '2. SOCIAL PROOF',
        content: '<p><strong>"10,000+ customers trust us"</strong></p><p>People follow the crowd. Show testimonials, reviews, and user counts to build instant <em>credibility</em>.</p>',
        emoji: 'ðŸ‘¥',
        category: '',
        accentColor: '#00D4FF',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1,
        backgroundColor: '#F8F8F8',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content', 'media'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: '3. RECIPROCITY',
        content: '<p><strong>"Here\'s a free guide"</strong></p><p>Give value first. When you help people, they naturally want to <em>return the favor</em> by buying from you.</p>',
        emoji: 'ðŸŽ',
        category: '',
        accentColor: '#00D4FF',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1,
        backgroundColor: '#FFFFFF',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content', 'media'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: '4. ANCHORING',
        content: '<p><strong>"Was $199, Now $99"</strong></p><p>The first price you see sets the <em>anchor</em>. The discount feels massive, even if $99 was always the plan.</p>',
        emoji: 'âš“',
        category: '',
        accentColor: '#00D4FF',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1,
        backgroundColor: '#F8F8F8',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content', 'media'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: '5. AUTHORITY',
        content: '<p><strong>"As seen on Forbes"</strong></p><p>Authority builds trust. Badges, certifications, and media mentions make customers feel <em>safe</em> to buy.</p>',
        emoji: 'ðŸ†',
        category: '',
        accentColor: '#00D4FF',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1,
        backgroundColor: '#FFFFFF',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content', 'media'],
        customBlocks: [],
      },
    ],
  },

  // Template 3: Productivity Hacks
  {
    id: 'productivity-hacks',
    name: 'âš¡ Productivity Hacks',
    description: 'Bold template for productivity tips',
    category: 'Productivity',
    slides: [
      {
        type: 'cover',
        title: 'YOU\'RE WORKING',
        subtitle: 'TOO HARD, NOT SMART',
        category: '',
        accentColor: '#FF3B30',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1,
        backgroundColor: '#FFF9F5',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'subtitle', 'media'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'TIME BLOCKING',
        content: '<p><strong>Stop multitasking</strong></p><p>Block 90-minute <em>focus sessions</em> for deep work.</p><p>Check email only 2x per day.</p>',
        emoji: 'ðŸ“…',
        category: '',
        accentColor: '#FF3B30',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1,
        backgroundColor: '#FFFFFF',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content', 'media'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'THE 2-MINUTE RULE',
        content: '<p>If it takes <strong>less than 2 minutes</strong>, do it now.</p><p>Don\'t add it to your to-do list. Small tasks pile up and create <em>mental clutter</em>.</p>',
        emoji: 'â±ï¸',
        category: '',
        accentColor: '#FF3B30',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1,
        backgroundColor: '#FFF9F5',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content', 'media'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'EAT THE FROG',
        content: '<p><strong>Do the hardest task first</strong></p><p>Your willpower is highest in the morning. Tackle the <em>most important</em> thing before distractions hit.</p>',
        emoji: 'ðŸ¸',
        category: '',
        accentColor: '#FF3B30',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1,
        backgroundColor: '#FFFFFF',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content', 'media'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'BATCH SIMILAR TASKS',
        content: '<p>Group similar tasks together:</p><ul><li>All calls in one block</li><li>All emails in one block</li><li>All writing in one block</li></ul><p><em>Context switching kills productivity</em></p>',
        emoji: 'ðŸ“¦',
        category: '',
        accentColor: '#FF3B30',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1,
        backgroundColor: '#FFF9F5',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content', 'media'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'RESULTS',
        content: '<p><strong>Work smarter:</strong></p><ul><li>âœ“ 3x more done</li><li>âœ“ Less stress</li><li>âœ“ More free time</li><li>âœ“ Better quality work</li></ul>',
        emoji: 'ðŸŽ¯',
        category: '',
        accentColor: '#FF3B30',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1,
        backgroundColor: '#FFFFFF',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content', 'media'],
        customBlocks: [],
      },
    ],
  },

  // Template 4: Social Media Growth
  {
    id: 'social-media-growth',
    name: 'ðŸ“± Social Media Growth',
    description: 'Bold template about growing on social media',
    category: 'Social Media',
    slides: [
      {
        type: 'cover',
        title: '0 TO 10K',
        subtitle: 'FOLLOWERS IN 90 DAYS',
        category: '',
        accentColor: '#34C759',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1,
        backgroundColor: '#F0FFF4',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'subtitle', 'media'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'POST CONSISTENTLY',
        content: '<p><strong>Daily posting wins</strong></p><p>The algorithm rewards <em>consistency</em> over quality. Post every day, even if it\'s not perfect.</p>',
        emoji: 'ðŸ“†',
        category: '',
        accentColor: '#34C759',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1,
        backgroundColor: '#FFFFFF',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content', 'media'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'HOOK IN 3 SECONDS',
        content: '<p>Your first line must <strong>stop the scroll</strong></p><ul><li>Ask a bold question</li><li>Make a shocking statement</li><li>Promise a quick win</li></ul>',
        emoji: 'ðŸŽ£',
        category: '',
        accentColor: '#34C759',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1,
        backgroundColor: '#F0FFF4',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content', 'media'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'ENGAGE FIRST',
        content: '<p><strong>Comment on 20 posts before posting yours</strong></p><p>The algorithm favors active users. Engage with others to <em>warm up</em> your account.</p>',
        emoji: 'ðŸ’¬',
        category: '',
        accentColor: '#34C759',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1,
        backgroundColor: '#FFFFFF',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content', 'media'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'USE CAROUSELS',
        content: '<p><strong>Carousels get 3x more reach</strong></p><p>Multi-slide posts keep people engaged longer. The algorithm <em>loves</em> that.</p>',
        emoji: 'ðŸ“¸',
        category: '',
        accentColor: '#34C759',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1,
        backgroundColor: '#F0FFF4',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content', 'media'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'YOUR FORMULA',
        content: '<p><strong>Growth formula:</strong></p><ul><li>âœ“ Post daily</li><li>âœ“ Strong hooks</li><li>âœ“ Engage 20+ people</li><li>âœ“ Use carousels</li></ul><p><em>Repeat for 90 days</em></p>',
        emoji: 'ðŸš€',
        category: '',
        accentColor: '#34C759',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1,
        backgroundColor: '#FFFFFF',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content', 'media'],
        customBlocks: [],
      },
    ],
  },

  // Template 5: Personal Branding
  {
    id: 'personal-branding',
    name: 'â­ Personal Branding',
    description: 'Bold template about building a personal brand',
    category: 'Business',
    slides: [
      {
        type: 'cover',
        title: 'YOUR BRAND IS',
        subtitle: 'WHAT PEOPLE SAY WHEN YOU LEAVE',
        category: '',
        accentColor: '#FF2D55',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1,
        backgroundColor: '#FFF5F7',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'subtitle', 'media'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'PICK ONE NICHE',
        content: '<p><strong>Don\'t be everything to everyone</strong></p><p>Choose <em>one specific</em> area where you excel. Specialists earn more than generalists.</p>',
        emoji: 'ðŸŽ¯',
        category: '',
        accentColor: '#FF2D55',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1,
        backgroundColor: '#FFFFFF',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content', 'media'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'SHOW YOUR FACE',
        content: '<p><strong>People buy from people</strong></p><p>Use your real photo. Share your story. Be <em>authentic</em>. Faceless brands are forgettable.</p>',
        emoji: 'ðŸ‘¤',
        category: '',
        accentColor: '#FF2D55',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1,
        backgroundColor: '#FFF5F7',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content', 'media'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'TEACH, DON\'T SELL',
        content: '<p><strong>Give away 90% of your knowledge</strong></p><p>Build trust by <em>helping first</em>. The 10% you charge for is implementation and support.</p>',
        emoji: 'ðŸ“š',
        category: '',
        accentColor: '#FF2D55',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1,
        backgroundColor: '#FFFFFF',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content', 'media'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'BE CONSISTENT',
        content: '<p><strong>Same colors, same style, same message</strong></p><p>Your brand should be <em>instantly recognizable</em> across all platforms.</p>',
        emoji: 'ðŸŽ¨',
        category: '',
        accentColor: '#FF2D55',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1,
        backgroundColor: '#FFF5F7',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content', 'media'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'START TODAY',
        content: '<p><strong>Your brand checklist:</strong></p><ul><li>âœ“ Define your niche</li><li>âœ“ Create a consistent look</li><li>âœ“ Share valuable content</li><li>âœ“ Engage daily</li></ul>',
        emoji: 'âœ¨',
        category: '',
        accentColor: '#FF2D55',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1,
        backgroundColor: '#FFFFFF',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content', 'media'],
        customBlocks: [],
      },
    ],
  },

  // ===== PREMIUM DESIGN TEMPLATES =====

  // 1. APPLE KEYNOTE STYLE
  {
    id: 'apple-keynote-minimal',
    name: 'ðŸŽ Apple Keynote',
    description: 'Inspired by Apple presentations - massive typography, minimal design',
    category: 'Premium Design',
    slides: [
      {
        type: 'cover',
        title: 'One more thing.',
        subtitle: '',
        category: '',
        accentColor: '#000000',
        handle: '',
        fontFamily: 'var(--font-inter)',
        fontScale: 2.5,
        backgroundColor: '#FFFFFF',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: '10x',
        content: '<p style="font-size: 2em; font-weight: 300; margin-top: 3rem;">Faster performance.<br/>Zero compromise.</p>',
        emoji: '',
        category: '',
        accentColor: '#007AFF',
        handle: '',
        fontFamily: 'var(--font-inter)',
        fontScale: 3,
        backgroundColor: '#FFFFFF',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'Beautiful.',
        content: '<p style="font-size: 1.8em; font-weight: 300;">Every detail matters.</p>',
        emoji: '',
        category: '',
        accentColor: '#007AFF',
        handle: '',
        fontFamily: 'var(--font-inter)',
        fontScale: 2.8,
        backgroundColor: '#F5F5F7',
        textColor: '#1D1D1F',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content'],
        customBlocks: [],
      },
    ],
  },

  // 2. BRUTALIST DESIGN
  {
    id: 'brutalist-raw',
    name: 'â¬› Brutalist',
    description: 'Raw, bold, asymmetric design - anti-design aesthetic',
    category: 'Premium Design',
    slides: [
      {
        type: 'cover',
        title: 'BREAK\nRULES',
        subtitle: 'NOT DESIGN',
        category: '',
        accentColor: '#FFFF00',
        handle: '',
        fontFamily: 'var(--font-oswald)',
        fontScale: 2,
        backgroundColor: '#000000',
        textColor: '#FFFFFF',
        textAlign: 'left',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'subtitle'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: '01',
        content: '<p style="font-size: 1.8em; line-height: 1.3;"><span style="background: #FFFF00; color: #000; padding: 8px 16px; font-weight: 900;">THINK</span><br/><br/>Different. Disruptive.<br/>Unapologetic.</p>',
        emoji: '',
        category: '',
        accentColor: '#FFFF00',
        handle: '',
        fontFamily: 'var(--font-oswald)',
        fontScale: 2.5,
        backgroundColor: '#1A1A1A',
        textColor: '#FFFFFF',
        textAlign: 'left',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'left',
        elementOrder: ['title', 'content'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: '02',
        content: '<p style="font-size: 1.6em;"><span style="background: #FFFF00; color: #000; padding: 6px 14px; font-weight: 900;">CREATE</span><br/><br/>Without boundaries<br/>Without permission<br/>Without fear</p>',
        emoji: '',
        category: '',
        accentColor: '#FFFF00',
        handle: '',
        fontFamily: 'var(--font-oswald)',
        fontScale: 2.5,
        backgroundColor: '#000000',
        textColor: '#FFFFFF',
        textAlign: 'left',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'left',
        elementOrder: ['title', 'content'],
        customBlocks: [],
      },
    ],
  },

  // 3. VOGUE EDITORIAL
  {
    id: 'vogue-editorial',
    name: 'ðŸ“° Editorial',
    description: 'High-fashion magazine style - Vogue/GQ inspired',
    category: 'Premium Design',
    slides: [
      {
        type: 'cover',
        title: 'VOGUE',
        subtitle: 'The Art of Storytelling',
        category: '',
        accentColor: '#DC143C',
        handle: '',
        fontFamily: 'var(--font-playfair)',
        fontScale: 2.2,
        backgroundColor: '#FFFFFF',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'subtitle'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'Chapter I',
        content: '<p style="font-size: 2em; font-style: italic; line-height: 1.6; font-family: var(--font-playfair);">"In the world of design,<br/>elegance speaks louder<br/>than words."</p><p style="font-size: 1.2em; margin-top: 2rem; opacity: 0.7;">â€” Design Philosophy, 2025</p>',
        emoji: '',
        category: '',
        accentColor: '#DC143C',
        handle: '',
        fontFamily: 'var(--font-playfair)',
        fontScale: 1,
        backgroundColor: '#F8F8F8',
        textColor: '#1A1A1A',
        textAlign: 'left',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'left',
        elementOrder: ['title', 'content'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'ESSENCE',
        content: '<p style="font-size: 1.6em; line-height: 1.8;">Sophistication in simplicity. Power in restraint. Beauty in intention. Every element serves a purpose. Every space tells a story.</p>',
        emoji: '',
        category: '',
        accentColor: '#DC143C',
        handle: '',
        fontFamily: 'var(--font-playfair)',
        fontScale: 1.3,
        backgroundColor: '#FFFFFF',
        textColor: '#000000',
        textAlign: 'left',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content'],
        customBlocks: [],
      },
    ],
  },

  // 4. NEON CYBERPUNK
  {
    id: 'neon-cyberpunk',
    name: 'ðŸŒƒ Neon Tokyo',
    description: 'Cyberpunk futuristic design with neon accents',
    category: 'Premium Design',
    slides: [
      {
        type: 'cover',
        title: 'CYBER',
        subtitle: '2049',
        category: '',
        accentColor: '#FF00FF',
        handle: '',
        fontFamily: 'var(--font-roboto-mono)',
        fontScale: 2.5,
        backgroundColor: '#0A0E27',
        textColor: '#00FFFF',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'subtitle'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: '> INITIATE_',
        content: '<p style="font-size: 1.8em; font-family: var(--font-roboto-mono); line-height: 1.8; color: #00FFFF;"><span style="color: #FF00FF;">></span> System online<br/><span style="color: #FF00FF;">></span> Neural link established<br/><span style="color: #FF00FF;">></span> Ready to transmit</p>',
        emoji: '',
        category: '',
        accentColor: '#00FFFF',
        handle: '',
        fontFamily: 'var(--font-roboto-mono)',
        fontScale: 1.2,
        backgroundColor: '#0F1419',
        textColor: '#00FFFF',
        textAlign: 'left',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'left',
        elementOrder: ['title', 'content'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: '[ DATA ]',
        content: '<div style="border: 2px solid #FF00FF; padding: 2.5rem; background: rgba(255, 0, 255, 0.05);"><p style="font-size: 1.6em; font-family: var(--font-roboto-mono); color: #00FFFF;">â–“â–“â–“â–“â–“â–“â–“â–“â–‘â–‘ 85%<br/><br/><span style="color: #FF00FF;">PERFORMANCE:</span> OPTIMAL<br/><span style="color: #FF00FF;">STATUS:</span> ACTIVE<br/><span style="color: #FF00FF;">SYNC:</span> COMPLETE</p></div>',
        emoji: '',
        category: '',
        accentColor: '#FF00FF',
        handle: '',
        fontFamily: 'var(--font-roboto-mono)',
        fontScale: 1,
        backgroundColor: '#0A0E27',
        textColor: '#00FFFF',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content'],
        customBlocks: [],
      },
    ],
  },

  // 5. STARTUP PITCH
  {
    id: 'startup-pitch',
    name: 'ðŸš€ Startup Pitch',
    description: 'Y Combinator style - clean, data-focused, professional',
    category: 'Premium Design',
    slides: [
      {
        type: 'cover',
        title: 'We\'re building the future of X',
        subtitle: '',
        category: '',
        accentColor: '#FF6154',
        handle: '',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.8,
        backgroundColor: '#FFFFFF',
        textColor: '#000000',
        textAlign: 'left',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'left',
        elementOrder: ['title'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'The Problem',
        content: '<p style="font-size: 1.8em; font-weight: 400; line-height: 1.6;">Current solutions are <span style="background: #FEE; color: #FF6154; padding: 4px 8px;">broken</span>.</p><p style="font-size: 1.4em; margin-top: 2rem; opacity: 0.7;">â€¢ 90% of users frustrated<br/>â€¢ $50B market inefficiency<br/>â€¢ No viable alternative</p>',
        emoji: '',
        category: '',
        accentColor: '#FF6154',
        handle: '',
        fontFamily: 'var(--font-inter)',
        fontScale: 1,
        backgroundColor: '#FAFAFA',
        textColor: '#1A1A1A',
        textAlign: 'left',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'left',
        elementOrder: ['title', 'content'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'Traction',
        content: '<div style="display: grid; grid-template-columns: 1fr 1fr; gap: 2rem; margin-top: 2rem;"><div style="background: #F0FDF4; padding: 2rem; border-radius: 12px; border-left: 4px solid #22C55E;"><p style="font-size: 3em; font-weight: 700; color: #22C55E; margin: 0;">10K</p><p style="font-size: 1.2em; opacity: 0.7; margin-top: 0.5rem;">Users</p></div><div style="background: #EFF6FF; padding: 2rem; border-radius: 12px; border-left: 4px solid #3B82F6;"><p style="font-size: 3em; font-weight: 700; color: #3B82F6; margin: 0;">$50K</p><p style="font-size: 1.2em; opacity: 0.7; margin-top: 0.5rem;">MRR</p></div></div>',
        emoji: '',
        category: '',
        accentColor: '#22C55E',
        handle: '',
        fontFamily: 'var(--font-inter)',
        fontScale: 1,
        backgroundColor: '#FFFFFF',
        textColor: '#000000',
        textAlign: 'left',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'left',
        elementOrder: ['title', 'content'],
        customBlocks: [],
      },
    ],
  },
];

// Professional Educational Templates crafted with a world-class product-designer aesthetic
export const PRO_TEMPLATES: CarouselTemplate[] = [
  // Template 1 â€“ Minimalist (Apple-like)
  {
    id: 'pro-minimalist-clarity',
    name: 'ðŸ§Š Clarity & Focus',
    description: 'Ultra-minimal, white space driven educational carousel',
    category: 'Education',
    slides: [
      {
        type: 'cover',
        title: 'DESIGN WITH',
        subtitle: 'CLARITY',
        category: '',
        accentColor: '#007AFF',
        handle: '@yourhandle',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.4,
        backgroundColor: '#FFFFFF',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'subtitle'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'REMOVE NOISE',
        content: '<p>Every extra element competes for attention. Strip away whatâ€™s non-essential.</p>',
        emoji: '',
        category: '',
        accentColor: '#007AFF',
        handle: '@yourhandle',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.1,
        backgroundColor: '#F8F9FA',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'WHITE SPACE',
        content: '<p>Space guides the eye. Itâ€™s not emptyâ€”itâ€™s active breathing room.</p>',
        emoji: '',
        category: '',
        accentColor: '#007AFF',
        handle: '@yourhandle',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.1,
        backgroundColor: '#FFFFFF',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content'],
        customBlocks: [],
      },
    ],
  },

  // Template 2 â€“ Bold Dark (Tesla-like)
  {
    id: 'pro-bold-energy',
    name: 'âš¡ Bold Energy',
    description: 'High-contrast dark educational carousel',
    category: 'Education',
    slides: [
      {
        type: 'cover',
        title: 'BOLD DESIGN',
        subtitle: 'MOVES PEOPLE',
        category: '',
        accentColor: '#E82127',
        handle: '@yourhandle',
        fontFamily: 'var(--font-sf-pro)',
        fontScale: 1.4,
        backgroundColor: '#0B0F19',
        textColor: '#FFFFFF',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'subtitle'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'CONTRAST',
        content: '<p>Bright accents on deep blacks draw instant focusâ€”use sparingly for punch.</p>',
        emoji: '',
        category: '',
        accentColor: '#E82127',
        handle: '@yourhandle',
        fontFamily: 'var(--font-sf-pro)',
        fontScale: 1.1,
        backgroundColor: '#161B27',
        textColor: '#FFFFFF',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'MOTION',
        content: '<p>Design for speedâ€”both visually and in performance. Perceived speed âŸ¹ happy users.</p>',
        emoji: '',
        category: '',
        accentColor: '#E82127',
        handle: '@yourhandle',
        fontFamily: 'var(--font-sf-pro)',
        fontScale: 1.1,
        backgroundColor: '#0B0F19',
        textColor: '#FFFFFF',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content'],
        customBlocks: [],
      },
    ],
  },

  // Template 3 â€“ Fluent (Microsoft-like)
  {
    id: 'pro-fluent-systems',
    name: 'ðŸŒ Fluent Systems',
    description: 'Microsoft Fluent inspired educational set',
    category: 'Education',
    slides: [
      {
        type: 'cover',
        title: 'DESIGN',
        subtitle: 'AT SCALE',
        category: '',
        accentColor: '#38A1F3',
        handle: '@yourhandle',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.4,
        backgroundColor: '#FFFFFF',
        textColor: '#1B1B1B',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'subtitle'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'LAYERS',
        content: '<p>Use depth, shadow, and light to create hierarchy without clutter.</p>',
        emoji: '',
        category: '',
        accentColor: '#38A1F3',
        handle: '@yourhandle',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.1,
        backgroundColor: '#F3F4F6',
        textColor: '#1B1B1B',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content'],
        customBlocks: [],
      },
      {
        type: 'content',
        title: 'ACCESSIBILITY',
        content: '<p>Colour, typography, motionâ€”design for everyone. Build inclusive experiences.</p>',
        emoji: '',
        category: '',
        accentColor: '#38A1F3',
        handle: '@yourhandle',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.1,
        backgroundColor: '#FFFFFF',
        textColor: '#1B1B1B',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content'],
        customBlocks: [],
      },
    ],
  },

  // Remaining 17 professional educational templates
  {
    id: 'pro-iterative-design',
    name: '🔄 Iterative Design',
    description: 'Ship → learn → refine. A lean approach to product improvements.',
    category: 'Education',
    slides: [
      { type: 'cover', title: 'ITERATE', subtitle: 'FASTER', category: '', accentColor: '#6366F1', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.3, backgroundColor: '#FFFFFF', textColor: '#000000', mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','subtitle'], customBlocks: [] },
      { type: 'content', title: 'BUILD', content: '<p>Create the smallest viable change.</p>', accentColor: '#6366F1', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.1, backgroundColor: '#F8F9FA', textColor: '#000000', mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','content'], customBlocks: [] },
      { type: 'content', title: 'MEASURE & LEARN', content: '<p>Use data to guide the next iteration.</p>', accentColor: '#6366F1', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.1, backgroundColor: '#FFFFFF', textColor: '#000000', mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','content'], customBlocks: [] },
    ],
  },
  {
    id: 'pro-customer-journey',
    name: '🗺️ Customer Journey',
    description: 'Mapping emotional peaks & valleys of users.',
    category: 'Education',
    slides: [
      { type: 'cover', title: 'JOURNEY', subtitle: 'MAPPING', accentColor: '#059669', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.3, backgroundColor: '#FFFFFF', textColor: '#000000', mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','subtitle'], customBlocks: [] },
      { type: 'content', title: 'EMPATHIZE', content: '<p>List feelings at every touch-point.</p>', accentColor: '#059669', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.1, backgroundColor: '#ECFDF5', textColor: '#000000', mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','content'], customBlocks: [] },
      { type: 'content', title: 'OPPORTUNITIES', content: '<p>Identify gaps to delight users.</p>', accentColor: '#059669', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.1, backgroundColor: '#FFFFFF', textColor: '#000000', mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','content'], customBlocks: [] },
    ],
  },
  {
    id: 'pro-data-driven',
    name: '📈 Data-Driven Decisions',
    description: 'Let numbers guide design without stifling creativity.',
    category: 'Education',
    slides: [
      { type: 'cover', title: 'DESIGN', subtitle: 'WITH DATA', accentColor: '#F59E0B', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.3, backgroundColor: '#FFFFFF', textColor: '#000000', mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','subtitle'], customBlocks: [] },
      { type: 'content', title: 'METRICS', content: '<p>Define success before you start.</p>', accentColor: '#F59E0B', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.1, backgroundColor: '#FFFBEB', textColor: '#000000', mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','content'], customBlocks: [] },
      { type: 'content', title: 'INSIGHTS', content: '<p>Pair quantitative data with qualitative stories.</p>', accentColor: '#F59E0B', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.1, backgroundColor: '#FFFFFF', textColor: '#000000', mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','content'], customBlocks: [] },
    ],
  },
  {
    id: 'pro-accessibility-first',
    name: '♿ Accessibility First',
    description: 'Inclusive design as default, not feature.',
    category: 'Education',
    slides: [
      { type: 'cover', title: 'INCLUSIVE', subtitle: 'DESIGN', accentColor: '#10B981', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.3, backgroundColor: '#FFFFFF', textColor: '#000000', mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','subtitle'], customBlocks: [] },
      { type: 'content', title: 'CONTRAST', content: '<p>Meet WCAG AA at minimum.</p>', accentColor: '#10B981', backgroundColor: '#ECFDF5', textColor: '#000000', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.1, mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','content'], customBlocks: [] },
      { type: 'content', title: 'KEYBOARD NAV', content: '<p>Everything reachable sans mouse.</p>', accentColor: '#10B981', backgroundColor: '#FFFFFF', textColor: '#000000', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.1, mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','content'], customBlocks: [] },
    ],
  },
  {
    id: 'pro-microinteractions',
    name: '🔔 Micro-interactions',
    description: 'Tiny details ⇒ huge delight.',
    category: 'Education',
    slides: [
      { type: 'cover', title: 'MICRO', subtitle: 'INTERACTIONS', accentColor: '#EF4444', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.3, backgroundColor: '#0F172A', textColor: '#FFFFFF', mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','subtitle'], customBlocks: [] },
      { type: 'content', title: 'FEEDBACK', content: '<p>Every action deserves a response.</p>', accentColor: '#EF4444', backgroundColor: '#1E293B', textColor: '#FFFFFF', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.1, mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','content'], customBlocks: [] },
      { type: 'content', title: 'PERSONALITY', content: '<p>Add brand voice through subtle motion & sound.</p>', accentColor: '#EF4444', backgroundColor: '#0F172A', textColor: '#FFFFFF', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.1, mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','content'], customBlocks: [] },
    ],
  },
  {
    id: 'pro-localization',
    name: '🌍 Localization',
    description: 'Design for every language & culture.',
    category: 'Education',
    slides: [
      { type: 'cover', title: 'GLOBAL', subtitle: 'DESIGN', accentColor: '#8B5CF6', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.3, backgroundColor: '#FFFFFF', textColor: '#000000', mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','subtitle'], customBlocks: [] },
      { type: 'content', title: 'TEXT EXPANSION', content: '<p>Accommodate 30% longer strings.</p>', accentColor: '#8B5CF6', backgroundColor: '#F5F3FF', textColor: '#000000', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.1, mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','content'], customBlocks: [] },
      { type: 'content', title: 'RTL SUPPORT', content: '<p>Mirror layouts properly for right-to-left scripts.</p>', accentColor: '#8B5CF6', backgroundColor: '#FFFFFF', textColor: '#000000', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.1, mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','content'], customBlocks: [] },
    ],
  },
  {
    id: 'pro-sustainability',
    name: '🌱 Sustainable UI',
    description: 'Design with environmental impact in mind.',
    category: 'Education',
    slides: [
      { type: 'cover', title: 'GREEN', subtitle: 'DESIGN', accentColor: '#16A34A', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.3, backgroundColor: '#F0FDF4', textColor: '#000000', mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','subtitle'], customBlocks: [] },
      { type: 'content', title: 'LIGHT ASSETS', content: '<p>Optimise images & code → less energy.</p>', accentColor: '#16A34A', backgroundColor: '#FFFFFF', textColor: '#000000', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.1, mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','content'], customBlocks: [] },
      { type: 'content', title: 'DARK MODE', content: '<p>OLED blacks can save battery on mobile.</p>', accentColor: '#16A34A', backgroundColor: '#F0FDF4', textColor: '#000000', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.1, mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','content'], customBlocks: [] },
    ],
  },
  {
    id: 'pro-voice-ui',
    name: '🎙️ Voice UI Basics',
    description: 'Conversational interfaces & auditory feedback.',
    category: 'Education',
    slides: [
      { type: 'cover', title: 'VOICE', subtitle: 'INTERFACES', accentColor: '#F97316', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.3, backgroundColor: '#FFFFFF', textColor: '#000000', mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','subtitle'], customBlocks: [] },
      { type: 'content', title: 'COMMANDS', content: '<p>Design clear intents & confirmations.</p>', accentColor: '#F97316', backgroundColor: '#FFF7ED', textColor: '#000000', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.1, mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','content'], customBlocks: [] },
      { type: 'content', title: 'ERROR HANDLING', content: '<p>Offer graceful fallback to touch/typing.</p>', accentColor: '#F97316', backgroundColor: '#FFFFFF', textColor: '#000000', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.1, mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','content'], customBlocks: [] },
    ],
  },
  {
    id: 'pro-ar-design',
    name: '🕶️ AR Design 101',
    description: 'Principles for augmented reality products.',
    category: 'Education',
    slides: [
      { type: 'cover', title: 'AUGMENTED', subtitle: 'REALITY', accentColor: '#0EA5E9', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.3, backgroundColor: '#0F172A', textColor: '#FFFFFF', mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','subtitle'], customBlocks: [] },
      { type: 'content', title: 'SPATIAL ANCHORS', content: '<p>Place objects where they make contextual sense.</p>', accentColor: '#0EA5E9', backgroundColor: '#1E293B', textColor: '#FFFFFF', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.1, mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','content'], customBlocks: [] },
      { type: 'content', title: 'ERGONOMICS', content: '<p>Minimise camera movement fatigue.</p>', accentColor: '#0EA5E9', backgroundColor: '#0F172A', textColor: '#FFFFFF', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.1, mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','content'], customBlocks: [] },
    ],
  },
  {
    id: 'pro-edge-cases',
    name: '🛡️ Design for Edge Cases',
    description: 'Prepare for the unexpected.',
    category: 'Education',
    slides: [
      { type: 'cover', title: 'EDGE', subtitle: 'CASES', accentColor: '#DC2626', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.3, backgroundColor: '#FFFFFF', textColor: '#000000', mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','subtitle'], customBlocks: [] },
      { type: 'content', title: 'EMPTY STATES', content: '<p>Guide users when there’s no data.</p>', accentColor: '#DC2626', backgroundColor: '#FEF2F2', textColor: '#000000', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.1, mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','content'], customBlocks: [] },
      { type: 'content', title: 'ERROR STATES', content: '<p>Help, don’t blame. Offer recovery steps.</p>', accentColor: '#DC2626', backgroundColor: '#FFFFFF', textColor: '#000000', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.1, mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','content'], customBlocks: [] },
    ],
  },
  {
    id: 'pro-loading-states',
    name: '⏳ Loading UX',
    description: 'Design perception of speed during wait times.',
    category: 'Education',
    slides: [
      { type: 'cover', title: 'LOADING', subtitle: 'EXPERIENCE', accentColor: '#4F46E5', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.3, backgroundColor: '#FFFFFF', textColor: '#000000', mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','subtitle'], customBlocks: [] },
      { type: 'content', title: 'SKELETON', content: '<p>Show structured placeholders, not spinners.</p>', accentColor: '#4F46E5', backgroundColor: '#EEF2FF', textColor: '#000000', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.1, mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','content'], customBlocks: [] },
      { type: 'content', title: 'PROGRESS', content: '<p>Give users perceived control with % complete.</p>', accentColor: '#4F46E5', backgroundColor: '#FFFFFF', textColor: '#000000', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.1, mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','content'], customBlocks: [] },
    ],
  },
  {
    id: 'pro-privacy-by-design',
    name: '🔒 Privacy-by-Design',
    description: 'Protecting users from the first wireframe.',
    category: 'Education',
    slides: [
      { type: 'cover', title: 'PRIVACY', subtitle: 'BY DESIGN', accentColor: '#0F766E', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.3, backgroundColor: '#ECFEFF', textColor: '#000000', mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','subtitle'], customBlocks: [] },
      { type: 'content', title: 'DATA MINIMISATION', content: '<p>Collect only what you truly need.</p>', accentColor: '#0F766E', backgroundColor: '#FFFFFF', textColor: '#000000', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.1, mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','content'], customBlocks: [] },
      { type: 'content', title: 'TRANSPARENCY', content: '<p>Explain why & where data goes in plain language.</p>', accentColor: '#0F766E', backgroundColor: '#ECFEFF', textColor: '#000000', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.1, mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','content'], customBlocks: [] },
    ],
  },
  {
    id: 'pro-modular-components',
    name: '🧩 Modular Components',
    description: 'Build once, reuse everywhere.',
    category: 'Education',
    slides: [
      { type: 'cover', title: 'MODULAR', subtitle: 'UI', accentColor: '#A16207', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.3, backgroundColor: '#FFFBEB', textColor: '#000000', mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','subtitle'], customBlocks: [] },
      { type: 'content', title: 'CONSISTENCY', content: '<p>Shared components enforce brand coherence.</p>', accentColor: '#A16207', backgroundColor: '#FFFFFF', textColor: '#000000', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.1, mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','content'], customBlocks: [] },
      { type: 'content', title: 'SPEED', content: '<p>Build screens via composition, not invention.</p>', accentColor: '#A16207', backgroundColor: '#FFFBEB', textColor: '#000000', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.1, mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','content'], customBlocks: [] },
    ],
  },
  {
    id: 'pro-design-tokens',
    name: '🔖 Design Tokens',
    description: 'Single source of truth for style values.',
    category: 'Education',
    slides: [
      { type: 'cover', title: 'DESIGN', subtitle: 'TOKENS', accentColor: '#D946EF', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.3, backgroundColor: '#FDF4FF', textColor: '#000000', mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','subtitle'], customBlocks: [] },
      { type: 'content', title: 'SCALABILITY', content: '<p>Update one value, propagate everywhere.</p>', accentColor: '#D946EF', backgroundColor: '#FFFFFF', textColor: '#000000', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.1, mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','content'], customBlocks: [] },
      { type: 'content', title: 'THEMING', content: '<p>Swap token sets to switch themes effortlessly.</p>', accentColor: '#D946EF', backgroundColor: '#FDF4FF', textColor: '#000000', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.1, mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','content'], customBlocks: [] },
    ],
  },
  {
    id: 'pro-onboarding',
    name: '🚀 Seamless Onboarding',
    description: 'Guide users to first value quickly.',
    category: 'Education',
    slides: [
      { type: 'cover', title: 'FIRST', subtitle: 'MILE', accentColor: '#3B82F6', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.3, backgroundColor: '#E0F2FE', textColor: '#000000', mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','subtitle'], customBlocks: [] },
      { type: 'content', title: 'PROGRESSIVE DISCLOSURE', content: '<p>Show advanced features later, not upfront.</p>', accentColor: '#3B82F6', backgroundColor: '#FFFFFF', textColor: '#000000', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.1, mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','content'], customBlocks: [] },
      { type: 'content', title: 'CELEBRATE SUCCESS', content: '<p>Reinforce milestones with delight.</p>', accentColor: '#3B82F6', backgroundColor: '#E0F2FE', textColor: '#000000', handle: '@yourhandle', fontFamily: 'var(--font-inter)', fontScale: 1.1, mediaType: null, mediaAspectRatio: 16/9, mediaWidthPercent: 100, mediaAlignment: 'center', elementOrder: ['title','content'], customBlocks: [] },
    ],
  },
  // end of 17 templates
];

// ===== 33 INSPIRED TEMPLATES =====
// Generated from design patterns inspired by:
// - Canva templates (modern, colorful, clean)
// - LinkedIn carousels (professional, bold typography)  
// - Instagram carousels (gradient, trendy, bold)
// - Dribbble/Behance (creative, artistic)
// - Modern design trends (minimalist, brutalist, editorial)

export const INSPIRED_TEMPLATES: CarouselTemplate[] = [
  // Canva Modern Style - Business Growth
  {
    id: 'canva-modern-business',
    name: 'Canva Modern: Business Growth',
    description: 'Modern, colorful design inspired by Canva templates - perfect for business content',
    category: 'Business Growth',
    slides: [
      {
        type: 'cover',
        title: 'BUSINESS GROWTH',
        subtitle: 'STRATEGIES THAT WORK',
        category: 'Business Growth',
        accentColor: '#FF6B9D',
        handle: '@yourhandle',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.4,
        backgroundColor: '#FFFFFF',
        textColor: '#1A1A1A',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'subtitle', 'content'],
        customBlocks: [],
        textAlign: 'center',
      },
      {
        type: 'content',
        title: 'WHY STRATEGY MATTERS',
        content: '<p style="font-size: 1.2em; line-height: 1.6;">Understanding business strategy is essential for success. Here\'s what you need to know to excel.</p>',
        emoji: '',
        category: 'Business Growth',
        accentColor: '#FF6B9D',
        handle: '@yourhandle',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.1,
        backgroundColor: '#F8F9FA',
        textColor: '#1A1A1A',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'subtitle', 'content'],
        customBlocks: [],
        textAlign: 'center',
      },
      {
        type: 'content',
        title: 'TAKE ACTION',
        content: '<p style="background: #FF6B9D20; padding: 2rem; border-radius: 8px; margin-top: 1rem; border-left: 4px solid #FF6B9D;"><strong style="font-size: 1.2em;">START TODAY</strong></p><p style="margin-top: 1.5rem;">Apply these business strategies and see immediate results.</p>',
        emoji: '',
        category: 'Business Growth',
        accentColor: '#FF6B9D',
        handle: '@yourhandle',
        fontFamily: 'var(--font-inter)',
        fontScale: 1.1,
        backgroundColor: '#FFFFFF',
        textColor: '#1A1A1A',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content'],
        customBlocks: [],
        textAlign: 'center',
      },
    ],
  },

  // LinkedIn Professional Style - Leadership
  {
    id: 'linkedin-professional-leadership',
    name: 'LinkedIn Professional: Leadership',
    description: 'Professional, bold design inspired by LinkedIn carousels',
    category: 'Leadership',
    slides: [
      {
        type: 'cover',
        title: 'LEADERSHIP',
        subtitle: 'PROFESSIONAL INSIGHTS',
        category: 'Leadership',
        accentColor: '#0077B5',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1.5,
        backgroundColor: '#FFFFFF',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'subtitle'],
        customBlocks: [],
        textAlign: 'center',
      },
      {
        type: 'content',
        title: 'WHY LEADERSHIP MATTERS',
        content: '<p style="font-size: 1.2em; line-height: 1.6;">Great leadership drives organizational success. Here\'s what separates good leaders from great ones.</p>',
        emoji: '',
        category: 'Leadership',
        accentColor: '#0077B5',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1.2,
        backgroundColor: '#F3F2EF',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content'],
        customBlocks: [],
        textAlign: 'center',
      },
      {
        type: 'content',
        title: 'KEY PRINCIPLES',
        content: '<p style="margin-bottom: 1rem;"><strong style="background: #0077B5; color: #FFF; padding: 6px 16px; display: inline-block; font-size: 1.2em;">PRINCIPLE #1</strong></p><p style="font-size: 1.1em;">Master these fundamentals to excel in leadership.</p>',
        emoji: '',
        category: 'Leadership',
        accentColor: '#0077B5',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1.2,
        backgroundColor: '#FFFFFF',
        textColor: '#000000',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content'],
        customBlocks: [],
        textAlign: 'center',
      },
    ],
  },

  // Instagram Trendy Style - Marketing
  {
    id: 'instagram-trendy-marketing',
    name: 'Instagram Trendy: Marketing',
    description: 'Trendy, gradient design inspired by Instagram carousels',
    category: 'Marketing',
    slides: [
      {
        type: 'cover',
        title: 'MARKETING',
        subtitle: 'TRENDING NOW',
        category: 'Marketing',
        accentColor: '#FFD700',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1.6,
        backgroundColor: '#667eea',
        textColor: '#FFFFFF',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'subtitle'],
        customBlocks: [],
        textAlign: 'center',
      },
      {
        type: 'content',
        title: 'WHY MARKETING MATTERS',
        content: '<p style="font-size: 1.2em; line-height: 1.6; color: #FFFFFF;">Understanding marketing is essential for business growth. Here\'s what you need to know.</p>',
        emoji: '',
        category: 'Marketing',
        accentColor: '#FFD700',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1.2,
        backgroundColor: '#764ba2',
        textColor: '#FFFFFF',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content'],
        customBlocks: [],
        textAlign: 'center',
      },
      {
        type: 'content',
        title: 'TAKE ACTION',
        content: '<p style="background: rgba(255, 215, 0, 0.2); padding: 2rem; border-radius: 8px; margin-top: 1rem; border-left: 4px solid #FFD700;"><strong style="font-size: 1.2em; color: #FFFFFF;">START TODAY</strong></p><p style="margin-top: 1.5rem; color: #FFFFFF;">Apply these marketing strategies and see immediate results.</p>',
        emoji: '',
        category: 'Marketing',
        accentColor: '#FFD700',
        handle: '@yourhandle',
        fontFamily: 'var(--font-oswald)',
        fontScale: 1.1,
        backgroundColor: '#667eea',
        textColor: '#FFFFFF',
        mediaType: null,
        mediaAspectRatio: 16 / 9,
        mediaWidthPercent: 100,
        mediaAlignment: 'center',
        elementOrder: ['title', 'content'],
        customBlocks: [],
        textAlign: 'center',
      },
    ],
  },,


,


,


,



];

// ---------- UPDATE EXPORT ----------
export const ALL_TEMPLATES = [...BOLD_TEMPLATES, ...PRO_TEMPLATES, ...INSPIRED_TEMPLATES];
